"""add goals table

Revision ID: 2026_05_27_1645_add_goals_table
Revises: 2026_05_27_1038_remove_kg_tables
Create Date: 2026-05-27 16:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2026_05_27_1645_add_goals_table'
down_revision: Union[str, None] = '2026_05_27_1038_remove_kg_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ABANDONED', name='goalstatusdb'), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('parent_goal_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_completed_at'), 'goals', ['completed_at'], unique=False)
    op.create_index(op.f('ix_goals_created_at'), 'goals', ['created_at'], unique=False)
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_index(op.f('ix_goals_parent_goal_id'), 'goals', ['parent_goal_id'], unique=False)
    op.create_index(op.f('ix_goals_status'), 'goals', ['status'], unique=False)
    op.create_index(op.f('ix_goals_target_date'), 'goals', ['target_date'], unique=False)
    op.create_index('idx_goal_status_created', 'goals', ['status', 'created_at'], unique=False)
    op.create_index('idx_goal_status_target', 'goals', ['status', 'target_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_goal_status_target', table_name='goals')
    op.drop_index('idx_goal_status_created', table_name='goals')
    op.drop_index(op.f('ix_goals_target_date'), table_name='goals')
    op.drop_index(op.f('ix_goals_status'), table_name='goals')
    op.drop_index(op.f('ix_goals_parent_goal_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_created_at'), table_name='goals')
    op.drop_index(op.f('ix_goals_completed_at'), table_name='goals')
    op.drop_table('goals')
    sa.Enum('ACTIVE', 'COMPLETED', 'ABANDONED', name='goalstatusdb').drop(op.get_bind())
    # ### end Alembic commands ###
