"""Phase 4 email tracking and conversation summaries

Revision ID: 8b924c237530
Revises: 9d73740fcff5
Create Date: 2026-02-22 14:56:48.016989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b924c237530'
down_revision: Union[str, Sequence[str], None] = '9d73740fcff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=256), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('messages_summarized', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_summaries_created_at'), 'conversation_summaries', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_summaries_session_id'), 'conversation_summaries', ['session_id'], unique=False)
    op.create_table('processed_emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(length=512), nullable=False),
    sa.Column('subject', sa.String(length=1024), nullable=True),
    sa.Column('sender', sa.String(length=512), nullable=True),
    sa.Column('action_taken', sa.String(length=256), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_emails_message_id'), 'processed_emails', ['message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_emails_message_id'), table_name='processed_emails')
    op.drop_table('processed_emails')
    op.drop_index(op.f('ix_conversation_summaries_session_id'), table_name='conversation_summaries')
    op.drop_index(op.f('ix_conversation_summaries_created_at'), table_name='conversation_summaries')
    op.drop_table('conversation_summaries')
    # ### end Alembic commands ###
