"""Initial schema with Pomodoro and Phase 3 updates

Revision ID: 9d73740fcff5
Revises: e67531817cd9
Create Date: 2026-02-22 14:01:02.024085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d73740fcff5'
down_revision: Union[str, Sequence[str], None] = 'e67531817cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pomodoro_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state', sa.Enum('IDLE', 'WORKING', 'SHORT_BREAK', 'LONG_BREAK', 'COMPLETED', 'PAUSED', name='pomodorostatedb'), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('work_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('short_break_minutes', sa.Integer(), nullable=False),
    sa.Column('long_break_minutes', sa.Integer(), nullable=False),
    sa.Column('cycles_completed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pomodoro_started_state', 'pomodoro_sessions', ['started_at', 'state'], unique=False)
    op.create_index('idx_pomodoro_state_created', 'pomodoro_sessions', ['state', 'created_at'], unique=False)
    op.create_index(op.f('ix_pomodoro_sessions_created_at'), 'pomodoro_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_pomodoro_sessions_id'), 'pomodoro_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_pomodoro_sessions_started_at'), 'pomodoro_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_pomodoro_sessions_state'), 'pomodoro_sessions', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pomodoro_sessions_state'), table_name='pomodoro_sessions')
    op.drop_index(op.f('ix_pomodoro_sessions_started_at'), table_name='pomodoro_sessions')
    op.drop_index(op.f('ix_pomodoro_sessions_id'), table_name='pomodoro_sessions')
    op.drop_index(op.f('ix_pomodoro_sessions_created_at'), table_name='pomodoro_sessions')
    op.drop_index('idx_pomodoro_state_created', table_name='pomodoro_sessions')
    op.drop_index('idx_pomodoro_started_state', table_name='pomodoro_sessions')
    op.drop_table('pomodoro_sessions')
    # ### end Alembic commands ###
