"""Initial Async PostgreSQL Migration

Revision ID: e67531817cd9
Revises:
Create Date: 2026-02-20 22:39:44.694063

"""

from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "e67531817cd9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
