"""Refactor DB Enums and UTC

Revision ID: 055ec74385e2
Revises: 
Create Date: 2026-01-03 22:17:58.037304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055ec74385e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('ACTIVE', 'CANCELLED', 'COMPLETED', name='eventstatus'),
               existing_nullable=True)

    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='reminderstatus'),
               existing_nullable=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('PENDING', 'COMPLETED', name='taskstatus'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'COMPLETED', name='taskstatus'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)

    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='reminderstatus'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('time',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('ACTIVE', 'CANCELLED', 'COMPLETED', name='eventstatus'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)

    # ### end Alembic commands ###

