"""
Generate training data for the Amadeus AI tool classifier model.

This script produces a JSON dataset of (text, tool_name) pairs covering
ALL tool categories registered in the Amadeus tool registry.

Coverage: ~50 tool labels, ~8,000+ labeled examples.
Rewritten 2026-04-10 to close the 27-tool coverage gap identified in the
classifier audit.
"""

import json
import random
import re
from pathlib import Path


# ---------------------------------------------------------------------------
# Templates — varied natural-language phrases per tool category
# ---------------------------------------------------------------------------
DATASET_TEMPLATES: dict[str, list[str]] = {
    # ===================================================================
    # INFO TOOLS  (info_tools.py)
    # ===================================================================
    "get_weather": [
        "What's the weather like in {city}?",
        "Is it raining in {city} right now?",
        "Give me the weather forecast for {city}",
        "Weather in {city}",
        "Will I need an umbrella in {city} tomorrow?",
        "How hot is it in {city}?",
        "Current temperature in {city}",
        "Is it going to rain tomorrow in {city}?",
        "Show me a 5-day forecast for {city}",
        "What is the humidity in {city}?",
        "How cold is it outside in {city}?",
        "Check the weather conditions in {city}",
        "Do I need a jacket in {city} today?",
        "Any chance of snow in {city}?",
        "What's the wind speed in {city}?",
        "Tell me the temperature outside",
        "Is it cloudy today?",
        "What's the forecast for this weekend?",
        "How's the weather looking?",
        "Will it be sunny in {city}?",
    ],
    "get_news": [
        "What's the latest news?",
        "Show me headlines for {topic}",
        "Get me the news about {topic}",
        "Any updates on {topic}?",
        "Read me the latest news.",
        "Breaking news today",
        "Top stories right now",
        "What's happening in the world?",
        "News headlines for today",
        "Give me a news summary",
        "Fetch current events about {topic}",
        "What are people talking about in {topic}?",
        "Show me recent {topic} news",
        "I want to hear the latest about {topic}",
        "Summarize today's news",
        "Any breaking stories?",
        "What's trending in the news?",
        "Top {topic} headlines",
        "Morning news briefing please",
        "Give me the daily news digest",
    ],
    "get_datetime_info": [
        "What time is it?",
        "What's the date today?",
        "Tell me the current time",
        "Is it morning or afternoon?",
        "What day of the week is it?",
        "Current date and time",
        "Give me the time",
        "What's today's date?",
        "How many days until the weekend?",
        "Is it past noon yet?",
        "Tell me the day and time",
        "What is the time right now?",
        "What month are we in?",
        "Show me a calendar for today",
        "Is it a weekday today?",
        "What year is it?",
        "Tell me the date",
        "Give me the current date and day",
        "What week number is this?",
        "Date please",
    ],
    "tell_joke": [
        "Tell me a joke",
        "Make me laugh",
        "Do you know any jokes?",
        "Tell a funny story",
        "I need a laugh",
        "Give me a joke",
        "Say something funny",
        "Tell me something humorous",
        "I'm bored, tell me a joke",
        "Do you have a good one-liner?",
        "A pun please",
        "Hit me with a joke",
        "What's your best joke?",
        "Tell me a dad joke",
        "Can you be funny?",
        "Got any good jokes?",
        "Crack a joke for me",
        "Any programming jokes?",
        "Entertain me with humor",
        "Know a knock-knock joke?",
    ],
    "calculate": [
        "Calculate {math}",
        "What is {math}?",
        "Solve {math}",
        "Math: {math}",
        "How much is {math}?",
        "Can you calculate {math}?",
        "Result of {math}",
        "Compute {math}",
        "What's the answer to {math}?",
        "Do the math: {math}",
        "Figure out {math}",
        "Work out {math}",
        "{math} equals what?",
        "Evaluate {math}",
        "Calculate for me: {math}",
        "Quick math: {math}",
        "What does {math} equal?",
        "Crunch the numbers: {math}",
        "Arithmetic: {math}",
        "Give me the result of {math}",
    ],
    "set_timer": [
        "Set a timer for {duration}",
        "Timer for {duration}",
        "Start a {duration} timer",
        "Count down {duration} please",
        "Countdown {duration}",
        "Set a {duration} countdown",
        "Time me for {duration}",
        "Run a timer for {duration}",
        "I need a timer for {duration}",
        "Alarm in {duration}",
        "Buzz me in {duration}",
        "Timer {duration} starting now",
        "Can you set a {duration} timer?",
        "Start the clock for {duration}",
        "Start countdown for {duration}",
    ],
    "convert_temperature": [
        "Convert {temp_val} degrees {temp_from} to {temp_to}",
        "What is {temp_val} {temp_from} in {temp_to}?",
        "{temp_val} {temp_from} to {temp_to}",
        "Temperature conversion: {temp_val} {temp_from} to {temp_to}",
        "How much is {temp_val}°{temp_from} in {temp_to}?",
        "Convert {temp_val}° Celsius to Fahrenheit",
        "What's {temp_val}F in Celsius?",
        "Change {temp_val} Kelvin to Celsius",
        "{temp_val} Fahrenheit in Celsius please",
        "Can you convert {temp_val} C to F?",
        "Temperature: {temp_val} {temp_from} → {temp_to}",
        "How many degrees Fahrenheit is {temp_val} Celsius?",
        "Turn {temp_val}°C into Fahrenheit",
        "What's the Fahrenheit equivalent of {temp_val} Celsius?",
        "Convert body temp 98.6F to Celsius",
    ],
    "convert_length": [
        "Convert {len_val} {len_from} to {len_to}",
        "What is {len_val} {len_from} in {len_to}?",
        "{len_val} {len_from} to {len_to}",
        "How many {len_to} in {len_val} {len_from}?",
        "Length conversion: {len_val} {len_from} to {len_to}",
        "Convert {len_val} miles to kilometers",
        "How many feet in {len_val} meters?",
        "Change {len_val} inches to centimeters",
        "{len_val} km to miles",
        "{len_val} cm in inches",
        "What's {len_val} yards in meters?",
        "How long is {len_val} feet in meters?",
        "Distance: {len_val} {len_from} → {len_to}",
        "Convert height 5 feet 11 inches to cm",
        "Meters to feet: {len_val}",
    ],
    "open_website": [
        "Open {url}",
        "Go to {url}",
        "Visit {url}",
        "Navigate to {url}",
        "Open the website {url}",
        "Browse to {url}",
        "Load {url} in the browser",
        "Pull up {url}",
        "Take me to {url}",
        "Open this link: {url}",
        "Google search for {topic}",
        "Search Google for {topic}",
        "Google {topic}",
        "Open a browser and go to {url}",
        "Show me the website {url}",
    ],
    # ===================================================================
    # WEB / SEARCH TOOLS
    # ===================================================================
    "web_search": [
        "Search the web for {topic}",
        "Find me information about {topic}",
        "Can you look up {topic}?",
        "Google search {topic}",
        "Find results for {topic}",
        "Search online for {topic}",
        "Find {topic}",
        "Look up {topic} on the internet",
        "Do a web search for {topic}",
        "Search for the latest on {topic}",
        "I need search results for {topic}",
        "Find websites about {topic}",
        "Run a search for {topic}",
        "What does the internet say about {topic}?",
        "Quick search: {topic}",
        "Search {topic} for me",
        "Web results for {topic}",
        "DDG search {topic}",
        "Look this up: {topic}",
        "Find info on {topic}",
    ],
    "wikipedia_search": [
        "Who is {person}?",
        "What is {concept}?",
        "Tell me about {topic}",
        "Look up {topic} on Wikipedia",
        "Give me a summary of {topic}",
        "Explain {concept} to me",
        "What does {concept} mean?",
        "Wikipedia article on {topic}",
        "Give me a brief history of {topic}",
        "Define {concept}",
        "How does {concept} work?",
        "What can you tell me about {person}?",
        "I want to learn about {concept}",
        "Describe {topic}",
        "Give me facts about {topic}",
        "Wiki {topic}",
        "Explain the concept of {concept}",
        "What's the definition of {concept}?",
        "Encyclopedia entry for {topic}",
        "Brief summary of {person}",
    ],
    "fetch_webpage_content": [
        "Fetch the content from {url}",
        "Open this link and summarize: {url}",
        "What does this webpage say: {url}?",
        "Read {url} for me",
        "Get information from this URL: {url}",
        "Scrape the contents of {url}",
        "What's on this site: {url}?",
        "Parse the content at {url}",
        "Extract text from {url}",
        "Summarize the article at {url}",
        "Visit and read: {url}",
        "Load the page at {url}",
        "Can you read this page: {url}?",
        "Get the text from this website: {url}",
        "Check what's on {url}",
        "Download text from {url}",
        "Analyze this webpage: {url}",
        "What's written on {url}?",
        "Read this URL and tell me what it says: {url}",
        "Pull the article from {url}",
    ],
    # ===================================================================
    # SYSTEM / MONITOR TOOLS  (monitor_tools.py)
    # ===================================================================
    "system_status": [
        "How is the system running?",
        "Check system status",
        "How much memory is free?",
        "System health report",
        "Are all services up?",
        "Status of the server",
        "Give me a system overview",
        "How is RAM doing?",
        "Is the system under load?",
        "What are the current system stats?",
        "Show me resource usage",
        "How busy is the machine?",
        "Run a quick diagnostics check",
        "System performance snapshot",
        "How's the computer doing?",
        "Quick system health check",
        "PC status",
        "Machine status report",
        "Overall system health?",
        "Show system performance",
        "Are resources okay?",
        "System perf check",
        "Is my computer healthy?",
        "System overview please",
        "Computer diagnostics",
        "System load summary",
        "Quick PC checkup",
        "Check computer performance",
        "How's my machine performing?",
        "General system check",
    ],
    "get_cpu_usage": [
        "What's the CPU usage right now?",
        "CPU load percentage?",
        "How hard is the CPU working?",
        "Is the processor overloaded?",
        "Check CPU usage",
        "Show me CPU consumption",
        "Processor stats please",
        "What percentage of CPU is being used?",
        "Any CPU spikes happening?",
        "Tell me about CPU usage",
        "CPU utilization?",
        "How's the CPU doing?",
        "Is the CPU maxed out?",
        "Current processor load?",
        "CPU % please",
        "How much CPU am I using?",
        "Check processor usage",
        "Processor utilization right now",
        "Is the CPU under heavy load?",
        "Show processor percentage",
        "What's the current CPU load?",
        "CPU usage stats",
        "How's the processor?",
        "CPU activity level?",
        "Is CPU usage high?",
        "Tell me CPU percent",
        "Check the processor load",
        "What's the CPU at?",
        "Current CPU stats",
        "Show me the CPU meter",
    ],
    "get_memory_info": [
        "How much RAM is available?",
        "What's the memory usage?",
        "Check RAM usage",
        "How much free memory do I have?",
        "RAM stats please",
        "Show memory consumption",
        "How full is the RAM?",
        "What percentage of memory is used?",
        "Tell me about memory usage",
        "Is memory running low?",
        "Available RAM?",
        "Memory utilization right now?",
        "How much RAM is being used?",
        "Free memory check",
        "How much of my RAM is taken?",
        "RAM percentage used?",
        "Memory status report",
        "Am I running out of memory?",
        "How much RAM remains?",
        "Show me RAM stats",
        "Total and used memory?",
        "What's eating up memory?",
        "Memory check please",
        "Is my RAM okay?",
        "How's memory looking?",
        "RAM utilization please",
        "What's the RAM at?",
        "Current memory report",
        "Virtual memory usage?",
        "RAM capacity remaining?",
    ],
    "get_battery_info": [
        "How much battery is left?",
        "Battery level?",
        "Is my laptop charging?",
        "Check battery status",
        "What's the battery percentage?",
        "Battery health report",
        "How long until my battery dies?",
        "Is power plugged in?",
        "Show battery info",
        "Is battery low?",
        "Am I on battery power?",
        "Battery charge level?",
        "How much charge do I have?",
        "Is the charger connected?",
        "What's my battery at?",
        "Battery remaining time?",
        "Power status?",
        "Check if I'm plugged in",
        "Am I on AC power?",
        "How's my battery doing?",
        "Battery percent please",
        "Is the laptop on power?",
        "Remaining battery life?",
        "Do I need to charge?",
        "Battery time left?",
        "Show me the battery meter",
        "Laptop charge status?",
        "Power supply status?",
        "How charged is my battery?",
        "Battery indicator?",
    ],
    "get_disk_info": [
        "How much disk space is left?",
        "Check disk usage",
        "Is the hard drive full?",
        "Storage space remaining?",
        "Disk capacity report",
        "Show me drive usage",
        "How full is my disk?",
        "Is storage running low?",
        "Free space on disk?",
        "What percentage of my disk is used?",
        "How much storage do I have left?",
        "Disk space check",
        "C drive free space?",
        "Is my SSD almost full?",
        "Storage status?",
        "Hard drive space remaining?",
        "Available storage?",
        "Show disk capacity",
        "Drive utilization?",
        "How much of my SSD is used?",
        "Storage report please",
        "Check hard drive space",
        "Disk usage percentage?",
        "Am I running out of storage?",
        "How's disk space looking?",
        "Any disk space left?",
        "Total vs used disk space?",
        "Storage space on main drive?",
        "Drive space report",
        "Is the disk getting full?",
    ],
    "get_network_info": [
        "Show network stats",
        "How much data have I sent?",
        "Network usage statistics",
        "Bytes sent and received?",
        "Check network activity",
        "What's my network traffic?",
        "How much data has been transferred?",
        "Network bandwidth usage?",
        "Data transfer stats",
        "Show me network I/O",
        "Network throughput?",
        "Internet data usage?",
        "How much have I downloaded today?",
        "Upload and download stats",
        "Network info please",
        "Total data sent and received?",
        "Network activity report",
        "How much data am I using?",
        "Internet traffic stats",
        "What's my data usage?",
        "Check internet activity",
        "Network transfer rate?",
        "Bandwidth consumption?",
        "How active is my network?",
        "Show data transfer totals",
        "Network I/O statistics",
        "Download volume?",
        "Upload volume?",
        "How much bandwidth am I using?",
        "Network transmission stats",
    ],
    "get_system_uptime": [
        "How long has the system been running?",
        "System uptime?",
        "When was the last reboot?",
        "How long since the last restart?",
        "Uptime report",
        "When was this computer last booted?",
        "Show me the uptime",
        "How long has the machine been on?",
        "Last boot time?",
        "When did I start this computer?",
        "How many hours has this been running?",
        "PC uptime?",
        "System boot time?",
        "How long since last shutdown?",
        "Machine uptime check",
        "How long has this been on?",
        "Tell me the uptime",
        "When was this machine turned on?",
        "Days since last reboot?",
        "Computer running time?",
        "How long ago was the last restart?",
        "Show boot timestamp",
        "Uptime in hours?",
        "Time since boot?",
        "Last restart date?",
        "When did the system start?",
        "Runtime duration?",
        "System on time?",
        "Hours running?",
        "Boot date and time?",
    ],
    "get_running_processes": [
        "What processes are running?",
        "Show me the top processes",
        "Which programs are using the most memory?",
        "List running processes",
        "What's consuming the most resources?",
        "Top processes by memory",
        "Show process list",
        "What applications are running right now?",
        "Memory-hungry processes?",
        "What's eating up my RAM?",
        "Task manager style report",
        "Show active processes",
        "Which processes are hogging CPU?",
        "List the heaviest running apps",
        "Top 10 processes",
        "What's running on my computer?",
        "Active process report",
        "Running apps list",
        "Top programs by resource usage",
        "Give me a process list",
        "What software is currently running?",
        "Show me running programs",
        "Process usage report",
        "Which apps are active?",
        "What programs are open?",
        "Heaviest processes right now?",
        "Running tasks list",
        "Show me what's running",
        "Resources by process",
        "Active programs report",
    ],
    "get_gpu_stats": [
        "What's my GPU usage?",
        "GPU load right now?",
        "Check GPU temperature",
        "GPU memory usage?",
        "How hot is the GPU?",
        "Show GPU stats",
        "Graphics card status?",
        "NVIDIA GPU utilization?",
        "Is the GPU overheating?",
        "What's the GPU temperature?",
        "GPU performance stats",
        "Graphics card load?",
        "How's my GPU doing?",
        "GPU VRAM usage?",
        "Check graphics card",
        "Show me GPU utilization",
        "GPU activity level?",
        "What's the graphics card at?",
        "GPU percentage used?",
        "Graphics memory usage?",
        "GPU thermal status",
        "Video card stats?",
        "Is the GPU under load?",
        "Check GPU performance",
        "GPU info please",
        "How much GPU is being used?",
        "Graphics processor status",
        "GPU compute usage?",
        "What's the GPU load?",
        "GPU health check",
    ],
    "get_temperature_sensors": [
        "What are my system temperatures?",
        "Check CPU temperature",
        "Hardware temperatures",
        "How hot is the CPU?",
        "Thermal readings",
        "Temperature sensor data",
        "Is anything overheating?",
        "Show thermal status",
        "Core temperatures?",
        "System thermal report",
        "CPU thermal reading",
        "Are my components running hot?",
        "Chip temperatures?",
        "Hardware temp check",
        "Sensor readings for temperature",
        "Component temps?",
        "What's the CPU temp?",
        "All temperature sensors",
        "Thermal monitoring report",
        "Heat sensor readings",
        "Is my CPU too hot?",
        "Show me temperature data",
        "Current thermal readings",
        "CPU core temps?",
        "Check if overheating",
        "Thermal status report",
        "System heat check",
        "Temperature across components",
        "Read thermal sensors",
        "Heat levels?",
    ],
    "check_system_alerts": [
        "Any system warnings?",
        "Check for performance alerts",
        "Are there any system alerts?",
        "System alert check",
        "Any warnings about CPU or memory?",
        "Performance alerts?",
        "Is anything wrong with the system?",
        "Check for hardware warnings",
        "System health warnings?",
        "Any critical alerts?",
        "Are there problems with my machine?",
        "Check if anything needs attention",
        "System warning report",
        "Alert status?",
        "Any red flags on the system?",
        "Check for critical issues",
        "Warning notifications?",
        "Any performance problems?",
        "System health alerts?",
        "Is anything over threshold?",
        "Check for system issues",
        "Hardware alert check",
        "Any danger zones on resources?",
        "Performance warning check",
        "Alert me to problems",
        "Check system for warnings",
        "Any issues detected?",
        "System problem report",
        "Critical resource alerts?",
        "Health alert status?",
    ],
    "get_full_system_report": [
        "Give me a full system report",
        "Complete system diagnostics",
        "Detailed system info",
        "Full hardware report",
        "Comprehensive system stats",
        "Everything about my system",
        "All system metrics",
        "Detailed performance report",
        "Full diagnostics please",
        "System information dump",
        "Complete PC report",
        "Show me all system details",
        "Run full system diagnostics",
        "Total system overview",
        "Exhaustive system check",
        "Complete machine diagnostic",
        "All metrics report",
        "Full hardware and software report",
        "Detailed computer info",
        "Show me everything about this PC",
        "In-depth system analysis",
        "Full performance audit",
        "System specs and performance",
        "Comprehensive diagnostics",
        "Thorough system report",
        "Complete system information",
        "Detailed health report",
        "All system specs",
        "Full machine report",
        "System deep dive",
    ],
    # ===================================================================
    # SYSTEM ACTION TOOLS  (system_tools.py)
    # ===================================================================
    "open_application": [
        "Open {app}",
        "Launch {app}",
        "Start {app}",
        "Run {app} please",
        "Can you open {app}?",
        "Boot up {app}",
        "Pull up {app}",
        "Bring up {app}",
        "Open the {app} application",
        "Start my {app}",
        "Fire up {app}",
        "Load {app} for me",
        "I need {app} open",
        "Open {app} on my computer",
        "Launch the {app} program",
    ],
    "terminate_program": [
        "Close {app}",
        "Kill {app}",
        "Stop {app}",
        "Terminate {app}",
        "End the {app} process",
        "Force quit {app}",
        "Shut down {app}",
        "Close the {app} application",
        "Kill the {app} process",
        "Can you close {app}?",
        "Exit {app}",
        "Stop running {app}",
        "End {app} task",
        "Force close {app}",
        "Quit {app} please",
    ],
    "scan_system_applications": [
        "Scan for installed apps",
        "Find new applications on my system",
        "Rebuild the app list",
        "Rescan installed programs",
        "Refresh application registry",
        "Discover installed software",
        "Update the app cache",
        "Scan system for new programs",
        "What apps are installed?",
        "Refresh the program list",
        "Find all installed applications",
        "Scan for newly installed software",
        "Rebuild app cache",
        "Detect installed programs",
        "Re-index my applications",
        "Rescan for new apps",
        "Discover new software",
        "Rebuild the program registry",
        "Force rescan applications",
        "Refresh installed programs",
        "Search for installed software",
        "Index installed apps",
        "Scan my computer for apps",
        "Re-discover applications",
        "Update app list",
        "Recache applications",
        "Inventory installed apps",
        "Discover programs on this PC",
        "Scan for software",
        "Refresh my app cache",
    ],
    "take_screenshot": [
        "Take a screenshot",
        "Capture my screen",
        "Screenshot now",
        "Take a screen capture",
        "Snap the screen",
        "Grab a screenshot",
        "Can you screenshot this?",
        "Screen capture please",
        "Save what's on my screen",
        "Capture the display",
        "Screenshot this please",
        "Print screen",
        "Grab the current screen",
        "Take a snapshot of my screen",
        "Screenshot the desktop",
        "Screengrab now",
        "Screen snapshot please",
        "Capture what I see",
        "Save a screenshot",
        "Please take a screencap",
        "Record the screen image",
        "Can you capture the screen?",
        "Get a screenshot",
        "Image of my screen",
        "Take a pic of the screen",
        "Screenshot for me please",
        "Save the display",
        "Grab my screen now",
        "Snap a screenshot",
        "Desktop capture",
    ],
    "search_file": [
        "Find the file {filename}",
        "Where is {filename}?",
        "Locate {filename} on my computer",
        "Search for {filename}",
        "Find files named {filename}",
        "Where did I save {filename}?",
        "Look for {filename} in my files",
        "Find {filename} in my documents",
        "Search my computer for {filename}",
        "Locate the file called {filename}",
        "Can you find {filename}?",
        "File search: {filename}",
        "Hunt for {filename}",
        "Where's the {filename} file?",
        "Do I have a file called {filename}?",
    ],
    "copy_file": [
        "Copy {filename} to {folder}",
        "Duplicate {filename}",
        "Copy the file {filename}",
        "Make a copy of {filename}",
        "Clone {filename} to {folder}",
        "Copy this file to my desktop",
        "Duplicate the document {filename}",
        "Create a backup copy of {filename}",
        "Copy {filename} to my Downloads",
        "Make a duplicate of {filename}",
        "Copy file from documents to desktop",
        "Backup {filename}",
        "Copy this to another folder",
        "Replicate {filename}",
        "Copy the report to {folder}",
    ],
    "move_file": [
        "Move {filename} to {folder}",
        "Transfer {filename} to {folder}",
        "Relocate {filename}",
        "Move the file {filename} to my desktop",
        "Move {filename} to Downloads",
        "Shift {filename} to {folder}",
        "Move this file to another location",
        "Transfer the document to {folder}",
        "Move {filename} from Documents to Desktop",
        "Relocate {filename} to {folder}",
        "Can you move {filename}?",
        "Move this file over",
        "File relocation: {filename} to {folder}",
        "Put {filename} in {folder}",
        "Move report to archive folder",
    ],
    "delete_file": [
        "Delete {filename}",
        "Remove {filename}",
        "Trash {filename}",
        "Get rid of {filename}",
        "Delete the file {filename}",
        "Erase {filename}",
        "Remove the file called {filename}",
        "Can you delete {filename}?",
        "Clean up {filename}",
        "Discard {filename}",
        "Throw away {filename}",
        "Delete this file please",
        "Permanently delete {filename}",
        "Remove the old {filename}",
        "Destroy {filename}",
    ],
    "create_folder": [
        "Create a folder called {folder}",
        "Make a new folder named {folder}",
        "New directory: {folder}",
        "Create directory {folder}",
        "Make folder {folder}",
        "Create a new folder on my desktop",
        "Make a project folder called {folder}",
        "Set up a folder named {folder}",
        "Create the {folder} directory",
        "Make me a folder called {folder}",
        "New folder: {folder}",
        "mkdir {folder}",
        "Create a subfolder named {folder}",
        "Set up a new directory",
        "Can you make a folder for {folder}?",
    ],
    # ===================================================================
    # SANDBOXED FILESYSTEM TOOLS  (filesystem_tools.py)
    # ===================================================================
    "fs_list_directory": [
        "List files in the workspace",
        "Show me what's in the workspace",
        "What files are in the agent directory?",
        "ls the workspace",
        "List workspace contents",
        "What files do you have?",
        "Show workspace directory",
        "Dir listing of workspace",
        "Browse workspace files",
        "What's in your folder?",
        "List your files",
        "Show the contents of your workspace",
        "What do you have stored?",
        "View workspace file list",
        "Check workspace contents",
        "Directory listing please",
        "What's in the agent workspace?",
        "List directory contents",
        "Show me everything in the workspace",
        "Browse agent directory",
        "What files exist in your folder?",
        "Show all files",
        "Workspace file inventory",
        "Contents of agent workspace?",
        "What's stored in the workspace?",
        "List all workspace files",
        "Agent folder contents",
        "View files in directory",
        "Show directory",
        "Files in your directory?",
    ],
    "fs_read_file": [
        "Read the file {filename} from workspace",
        "Show me the contents of {filename}",
        "Open {filename} from your workspace",
        "What does {filename} contain?",
        "Display {filename}",
        "Cat {filename}",
        "Read {filename} for me",
        "Print the contents of {filename}",
        "Show {filename} content",
        "Let me see {filename}",
        "View the file {filename}",
        "What's written in {filename}?",
        "Open and read {filename}",
        "Get the text from {filename}",
        "Read out {filename}",
    ],
    "fs_write_file": [
        "Write a file called {filename} with this content",
        "Save this text to {filename}",
        "Create a file named {filename}",
        "Write to {filename} in workspace",
        "Save to file: {filename}",
        "Store this in a file called {filename}",
        "Write this down to {filename}",
        "Put this content in {filename}",
        "Create {filename} with this text",
        "Save the output to {filename}",
        "Write a new file {filename}",
        "Dump this to {filename}",
        "Create and save {filename}",
        "Output to file {filename}",
        "Save as {filename}",
    ],
    "fs_search_files": [
        "Search for {filename} in workspace",
        "Find {filename} in your files",
        "Look for {filename} in the workspace",
        "Search workspace for {filename}",
        "Grep workspace for {filename}",
        "Any files matching {filename}?",
        "Do you have a file like {filename}?",
        "Locate {filename} in workspace",
        "File search in workspace: {filename}",
        "Hunt for {filename} in your directory",
        "Find files matching {filename} in workspace",
        "Workspace file lookup: {filename}",
        "Search your directory for {filename}",
        "Check for {filename} in workspace",
        "Any file named {filename} in your folder?",
    ],
    # ===================================================================
    # PRODUCTIVITY TOOLS  (productivity_tools.py)
    # ===================================================================
    "create_task": [
        "Add '{task}' to my todo list",
        "Create a new task: {task}",
        "Note down that I need to {task}",
        "Add a task: {task}",
        "Put '{task}' on my tasks",
        "Create task to {task}",
        "Remember to {task}",
        "Add to my task list: {task}",
        "I want to add a task for {task}",
        "New todo item: {task}",
        "Track a task for me: {task}",
        "Add to my checklist: {task}",
        "Task reminder to {task}",
        "Keep track of: {task}",
        "Add this to my list: {task}",
        "New task: {task}",
        "Todo: {task}",
        "Put {task} on my to-do",
        "I need to {task}, add it",
        "Add {task} as a task",
    ],
    "list_tasks": [
        "Show me my tasks",
        "What's on my todo list?",
        "List all my pending tasks",
        "What do I have to do?",
        "Show my to-do list",
        "What tasks are open?",
        "Display my task list",
        "Remind me what's on my list",
        "What are my current tasks?",
        "Check my tasks",
        "Any pending tasks?",
        "View my todo list",
        "What's left on my list?",
        "Show all tasks",
        "Pull up my task list",
        "Show me what I need to do",
        "My task list please",
        "Tasks overview",
        "What's on my plate?",
        "View current tasks",
        "Display all todos",
        "Give me my task list",
        "Pending task list",
        "What are my open items?",
        "Show to-do items",
        "Tasks I need to finish",
        "My pending work items",
        "Check my todo",
        "All my to-do items",
        "Current to-do list",
    ],
    "complete_task": [
        "Mark '{task}' as done",
        "Complete task: {task}",
        "I've finished {task}",
        "Check off {task}",
        "Task done: {task}",
        "I completed {task}",
        "Mark as complete: {task}",
        "Finish task {task}",
        "Close the task for {task}",
        "Done with {task}",
        "{task} is finished",
        "Tick off {task}",
        "I did {task}",
        "Cross off {task} from my list",
        "Complete: {task}",
    ],
    "get_task_summary": [
        "How many tasks do I have?",
        "Task summary please",
        "Give me a task overview",
        "Summary of my tasks",
        "How many pending tasks?",
        "Task count?",
        "How many todos left?",
        "What's my task status?",
        "Tasks stats",
        "Overview of my todo list",
        "Total tasks?",
        "How many tasks completed?",
        "Pending vs completed tasks?",
        "Quick task stats",
        "How am I doing on tasks?",
        "Task statistics",
        "My task numbers",
        "Number of tasks remaining",
        "Task completion rate",
        "Todo summary report",
        "Give me my task count",
        "Summary of pending and completed",
        "How many items on my list?",
        "Task totals please",
        "Progress on my tasks",
        "Am I on track with tasks?",
        "Task progress summary",
        "Todo completion status",
        "How productive have I been?",
        "Snapshot of my tasks",
    ],
    "set_reminder": [
        "Remind me to {task} at {time}",
        "Set a reminder for {task}",
        "Create a reminder: {task}",
        "I need a reminder for {time} to {task}",
        "Remind me about {task}",
        "Add a reminder to {task}",
        "Set alarm for {task}",
        "Alert me to {task} at {time}",
        "Don't let me forget to {task}",
        "Ping me when I need to {task}",
        "Schedule a reminder for {task}",
        "Remind me {time} to {task}",
        "Set a notification for {task}",
        "I want a reminder at {time} for {task}",
        "Kick me at {time} to {task}",
        "Remind me later to {task}",
        "Reminder: {task}",
        "Set an alert for {task}",
        "Remind me tomorrow to {task}",
        "Don't let me forget: {task}",
    ],
    "list_reminders": [
        "Show my reminders",
        "What reminders are set?",
        "List all my reminders",
        "Any upcoming reminders?",
        "Display my reminders",
        "What alerts do I have?",
        "Show active reminders",
        "Do I have any reminders?",
        "View my reminders",
        "Check my reminders",
        "Scheduled reminders?",
        "What's coming up in my reminders?",
        "Upcoming reminder list",
        "Pull up my reminders",
        "Any reminders due today?",
        "What am I being reminded about?",
        "My notification list",
        "Pending reminders?",
        "Active alerts list",
        "Show all pending reminders",
        "Any scheduled alerts?",
        "Reminder overview",
        "List my alerts and reminders",
        "What notifications are queued?",
        "Reminder status",
        "My scheduled reminders",
        "Future reminders list",
        "Show upcoming alerts",
        "What's on my reminder list?",
        "Check pending notifications",
    ],
    "create_note": [
        "Write a note: {note}",
        "Take a note about {note}",
        "Note this down: {note}",
        "Add a note for {note}",
        "Remember this: {note}",
        "Save a note: {note}",
        "Jot this down: {note}",
        "Create a note saying {note}",
        "Keep a record of {note}",
        "Quick note: {note}",
        "Write this down: {note}",
        "New note: {note}",
        "Make a note about {note}",
        "Take note of: {note}",
        "Save this for later: {note}",
    ],
    "list_notes": [
        "Show me my notes",
        "List all my notes",
        "What notes do I have?",
        "Display my notes",
        "View my notes",
        "Pull up my notes",
        "Any saved notes?",
        "Show my saved notes",
        "Note list please",
        "What did I write down?",
        "Check my notes",
        "All my notes",
        "Show recent notes",
        "View note history",
        "Open my notes",
        "List my saved notes",
        "Notes I've created",
        "My note collection",
        "Browse my notes",
        "What have I noted down?",
        "Show all saved notes",
        "Previously written notes",
        "All notes please",
        "My notebook contents",
        "Show everything I noted",
        "Notes overview",
        "Previous notes?",
        "Check what I wrote down",
        "All my written notes",
        "Notes archive",
    ],
    "get_note": [
        "Read note {note}",
        "Show me the note about {note}",
        "Open the note called {note}",
        "View note {note}",
        "What does note {note} say?",
        "Get note number {note}",
        "Read my {note} note",
        "Display note {note}",
        "Pull up note {note}",
        "Let me see note {note}",
        "Find the note about {note}",
        "Open note ID {note}",
        "Show note with title {note}",
        "Retrieve the {note} note",
        "What's in the {note} note?",
    ],
    "start_pomodoro": [
        "Start a pomodoro timer",
        "Begin a focus session",
        "Start the pomodoro",
        "Activate pomodoro mode",
        "Let's do a focus block",
        "Help me focus with a pomodoro",
        "Start a 25-minute work session",
        "Begin focused work mode",
        "Pomodoro time!",
        "Start work timer",
        "Focus session please",
        "Start pomodoro for {task}",
        "Kick off a pomodoro",
        "I need to focus, start pomodoro",
        "Begin pomodoro timer",
        "Pomodoro start",
        "Start focus mode",
        "Begin deep work session",
        "Turn on pomodoro",
        "Launch a pomodoro",
        "Go into focus mode",
        "Focus block please",
        "Start a productivity timer",
        "Begin a work sprint",
        "Pomodoro for 25 minutes",
        "Start concentration mode",
        "Begin the work timer",
        "Initiate pomodoro",
        "Focus time!",
        "Start my focus timer",
    ],
    "stop_pomodoro": [
        "Stop the pomodoro",
        "End the pomodoro session",
        "Cancel the pomodoro",
        "Stop pomodoro timer",
        "End my focus session",
        "Cancel my pomodoro",
        "I'm done with the pomodoro",
        "Kill the pomodoro timer",
        "Stop the focus timer",
        "Quit the pomodoro",
        "Pomodoro stop",
        "End focus mode",
        "Stop the work timer",
        "Cancel focus session",
        "I want to stop the pomodoro",
        "Finish the pomodoro early",
        "Abort the pomodoro",
        "Turn off pomodoro",
        "Pomodoro cancel",
        "End the focus timer",
        "Stop my work session",
        "Kill the focus session",
        "I'm stopping the pomodoro",
        "Halt the pomodoro timer",
        "Deactivate pomodoro",
        "Exit focus mode",
        "Break the pomodoro",
        "Pomodoro off",
        "Stop productivity timer",
        "End concentration mode",
    ],
    "pomodoro_status": [
        "How much time is left on my pomodoro?",
        "Pomodoro status",
        "Where am I in my pomodoro?",
        "Check pomodoro progress",
        "How's my focus session going?",
        "Pomodoro timer status",
        "Am I in a pomodoro right now?",
        "Time remaining on pomodoro?",
        "Is the pomodoro still running?",
        "How many pomodoros have I done today?",
        "Pomodoro cycle count?",
        "Focus session update",
        "Status of my work timer",
        "Current pomodoro progress",
        "How far into the pomodoro am I?",
        "Pomodoro time left?",
        "Work session status",
        "Focus timer remaining?",
        "Minutes left on pomodoro?",
        "Pomodoro check",
        "Is my focus session active?",
        "How many focus cycles today?",
        "Check my work timer",
        "Productivity timer status",
        "Pomodoro progress check",
        "Focus mode status?",
        "Am I in focus mode?",
        "How's the pomodoro going?",
        "Work sprint status",
        "Pomodoro timer check",
    ],
    "schedule_future_task": [
        "Schedule a task in {minutes} minutes",
        "In {minutes} minutes, remind me to {task}",
        "Schedule for later: {task}",
        "Auto-run {task} in {minutes} minutes",
        "Set up a future task for {task}",
        "Proactively follow up on {task} in {minutes} minutes",
        "Delay task by {minutes} minutes: {task}",
        "Queue a background task for {task}",
        "Schedule a follow-up in {minutes} minutes",
        "Set a timed action: {task} in {minutes} min",
        "Do {task} in {minutes} minutes automatically",
        "Execute {task} later in {minutes} min",
        "Schedule: {task} at {minutes} min from now",
        "Run this in {minutes} minutes: {task}",
        "Autonomous follow-up in {minutes} min",
    ],
    # ===================================================================
    # COMMUNICATION TOOLS  (slack_tools.py, email_tools.py, office_tools.py)
    # ===================================================================
    "send_slack_message": [
        "Send a Slack message to {slack_channel}",
        "Post in {slack_channel} on Slack",
        "Slack message to {slack_channel}: {note}",
        "Post this to Slack: {note}",
        "Send to Slack channel {slack_channel}",
        "Message {slack_channel} on Slack",
        "Slack: post to {slack_channel}",
        "Drop a message in {slack_channel} on Slack",
        "Write in {slack_channel} Slack channel",
        "Send this to Slack {slack_channel}",
        "Post a Slack update to {slack_channel}",
        "Slack DM to {slack_channel}",
        "Notify {slack_channel} on Slack",
        "Post on Slack: {note}",
        "Slack the team in {slack_channel}",
    ],
    "list_slack_channels": [
        "List Slack channels",
        "Show me all Slack channels",
        "What Slack channels are there?",
        "Slack channel list",
        "Which channels are on Slack?",
        "Available Slack channels?",
        "Show Slack workspace channels",
        "Get Slack channel names",
        "What channels do we have on Slack?",
        "List all Slack channels in workspace",
        "Display Slack channels",
        "Slack channels overview",
        "Browse Slack channels",
        "Show public Slack channels",
        "What Slack rooms exist?",
        "All channels in Slack",
        "View Slack channels list",
        "Give me the Slack channel list",
        "Show channels on Slack workspace",
        "Enumerate Slack channels",
        "Which Slack channels can I join?",
        "See all Slack rooms",
        "Slack workspace channel names",
        "What groups are on Slack?",
        "Show me the Slack directory",
        "Channels available on Slack?",
        "Channel list for Slack",
        "Workspace channels?",
        "Get available Slack channels",
        "Pull up Slack channel list",
    ],
    "read_slack_messages": [
        "Read messages from {slack_channel} on Slack",
        "Show me recent Slack messages in {slack_channel}",
        "What's being said in {slack_channel}?",
        "Get messages from Slack {slack_channel}",
        "Read Slack {slack_channel} chat",
        "Latest messages in {slack_channel} on Slack",
        "Slack history for {slack_channel}",
        "What did people say in {slack_channel}?",
        "Recent Slack posts in {slack_channel}",
        "Pull up Slack messages from {slack_channel}",
        "Check Slack {slack_channel} messages",
        "Show Slack conversation in {slack_channel}",
        "Read {slack_channel} Slack chat history",
        "Catch up on {slack_channel} Slack messages",
        "What's new in {slack_channel} on Slack?",
    ],
    "send_email": [
        "Send an email to {email}",
        "Email {email} about {note}",
        "Compose an email to {email}",
        "Write an email to {email}",
        "Send email: subject {note}",
        "Fire off an email to {email}",
        "Draft and send email to {email}",
        "Mail {email} with subject {note}",
        "Send a message via email to {email}",
        "Email this to {email}",
        "Dispatch an email to {email}",
        "Can you email {email} for me?",
        "Send {email} an email about {note}",
        "Shoot an email to {email}",
        "Compose and send to {email}",
    ],
    "read_emails": [
        "Check my email",
        "Any new emails?",
        "Read my unread emails",
        "Show me my inbox",
        "What emails have I received?",
        "Read latest emails",
        "Check for new mail",
        "Open my email inbox",
        "Show unread messages",
        "Any mail for me?",
        "Pull up my emails",
        "What's in my inbox?",
        "Read my recent emails",
        "Email inbox check",
        "Show me new emails",
        "What new mail do I have?",
        "Inbox summary",
        "Go through my emails",
        "Check my mailbox",
        "Any messages in my inbox?",
        "Read my mail",
        "Show inbox",
        "Look at my emails",
        "Fetch my unread mail",
        "Email check please",
        "Have I received any emails?",
        "New messages in my inbox?",
        "Review my email",
        "Get my emails",
        "Unread email count?",
    ],
    # ===================================================================
    # OFFICE TOOLS  (office_tools.py)
    # ===================================================================
    "create_excel_spreadsheet": [
        "Create an Excel spreadsheet",
        "Make a new spreadsheet called {filename}",
        "Create an Excel file with columns {note}",
        "Build a spreadsheet for {note}",
        "New Excel workbook please",
        "Generate an Excel file named {filename}",
        "Create a budget spreadsheet",
        "Make me an Excel sheet",
        "Set up a spreadsheet for tracking {note}",
        "Start a new Excel document",
        "Create a data table in Excel",
        "Excel file: {filename}",
        "Make a new .xlsx file",
        "Spreadsheet with this data",
        "Create an Excel report",
    ],
    "read_excel_spreadsheet": [
        "Read the Excel file {filename}",
        "Open the spreadsheet {filename}",
        "Show me the data in {filename}",
        "What's in the Excel file {filename}?",
        "Read spreadsheet {filename}",
        "Get data from {filename}.xlsx",
        "Open and read {filename} Excel file",
        "Display the spreadsheet {filename}",
        "Pull data from {filename}",
        "View the Excel file {filename}",
        "Read the {filename} workbook",
        "Show spreadsheet contents",
        "Get Excel data from {filename}",
        "Read the budget spreadsheet",
        "Open my expense spreadsheet",
    ],
    "create_word_document": [
        "Create a Word document",
        "Make a new Word doc called {filename}",
        "Create a document titled {note}",
        "Write a Word document about {note}",
        "Generate a Word file named {filename}",
        "Create a .docx file",
        "New Word doc please",
        "Draft a document about {note}",
        "Make me a Word document",
        "Create a report document",
        "Write a document for {note}",
        "New Word file: {filename}",
        "Set up a Word document",
        "Create a letter in Word",
        "Make a Word file with this content",
    ],
    # ===================================================================
    # CONVERSATIONAL (no tool needed)
    # ===================================================================
    "conversational": [
        "Hello there!",
        "How are you doing?",
        "Good morning Amadeus",
        "What's your name?",
        "I'm feeling great today",
        "Thanks for your help",
        "You are a great assistant",
        "Who created you?",
        "Let's chat for a bit",
        "I'm bored",
        "Hi",
        "Hey",
        "Okay, thanks",
        "You're awesome",
        "What can you do?",
        "Tell me about yourself",
        "I appreciate your help",
        "Bye, see you later",
        "Can we talk?",
        "What are you?",
        "How smart are you?",
        "Interesting!",
        "I agree with you",
        "Thank you so much",
        "That's helpful",
        "Good evening",
        "Good afternoon",
        "Good night",
        "Greet me",
        "Hello Amadeus",
        "Nice to meet you",
        "How do you work?",
        "What are your capabilities?",
        "You're very helpful",
        "Goodbye",
    ],
}

# ---------------------------------------------------------------------------
# Fillers — slot values for template placeholders
# ---------------------------------------------------------------------------
FILLERS: dict[str, list[str]] = {
    "city": [
        "New York",
        "London",
        "Tokyo",
        "Paris",
        "Mumbai",
        "Sydney",
        "Dubai",
        "Chicago",
        "the city",
        "here",
        "Berlin",
        "Singapore",
        "Los Angeles",
        "Toronto",
        "Mexico City",
    ],
    "topic": [
        "AI",
        "technology",
        "sports",
        "politics",
        "movies",
        "market",
        "science",
        "space",
        "climate change",
        "cryptocurrency",
        "fashion",
        "health",
        "music",
        "gaming",
        "finance",
    ],
    "person": [
        "Albert Einstein",
        "Elon Musk",
        "Marie Curie",
        "Steve Jobs",
        "the president",
        "Nikola Tesla",
        "Ada Lovelace",
        "Alan Turing",
        "Barack Obama",
        "Mahatma Gandhi",
    ],
    "concept": [
        "quantum physics",
        "machine learning",
        "black holes",
        "blockchain",
        "photosynthesis",
        "relativity",
        "DNA",
        "cloud computing",
        "neural networks",
        "evolution",
    ],
    "task": [
        "call mom",
        "buy groceries",
        "finish report",
        "pay bills",
        "walk the dog",
        "book tickets",
        "read a book",
        "reply to emails",
        "exercise",
        "prepare presentation",
    ],
    "time": [
        "3 PM",
        "tomorrow morning",
        "in an hour",
        "tonight",
        "next week",
        "at noon",
        "in 30 minutes",
        "before dinner",
        "at 9 AM",
        "this evening",
    ],
    "math": [
        "2+2",
        "15 * 6",
        "100 / 4",
        "sqrt(144)",
        "50% of 200",
        "5^3",
        "17 * 13",
        "1000 - 250",
        "45 + 89",
        "360 / 12",
    ],
    "note": [
        "meeting notes from Monday",
        "grocery list",
        "project ideas",
        "personal journal entry",
        "code snippet for later",
        "design feedback",
        "brainstorm session notes",
        "book recommendations",
        "travel itinerary",
        "recipe ingredients",
    ],
    "app": [
        "Chrome",
        "Notepad",
        "VS Code",
        "Spotify",
        "Calculator",
        "Teams",
        "Word",
        "Excel",
        "Discord",
        "Terminal",
    ],
    "minutes": ["5", "10", "15", "30", "60", "120"],
    "url": [
        "https://example.com",
        "https://news.ycombinator.com",
        "https://python.org",
        "https://wikipedia.org",
        "https://techcrunch.com",
        "https://github.com",
        "https://reddit.com",
        "https://stackoverflow.com",
    ],
    "duration": [
        "5 minutes",
        "10 minutes",
        "15 minutes",
        "30 minutes",
        "1 hour",
        "2 minutes",
        "45 seconds",
        "3 minutes",
        "20 minutes",
        "1 minute",
    ],
    "temp_val": ["100", "0", "32", "212", "37", "98.6", "20", "72", "350", "273"],
    "temp_from": ["Celsius", "Fahrenheit", "Kelvin", "C", "F", "K"],
    "temp_to": ["Celsius", "Fahrenheit", "Kelvin", "C", "F", "K"],
    "len_val": ["10", "100", "5", "26.2", "1", "42", "6", "1000", "2.5", "50"],
    "len_from": ["km", "miles", "meters", "feet", "inches", "cm", "yards", "mm"],
    "len_to": ["km", "miles", "meters", "feet", "inches", "cm", "yards", "mm"],
    "filename": [
        "report.txt",
        "notes.md",
        "data.csv",
        "budget.xlsx",
        "presentation.pptx",
        "photo.png",
        "readme.md",
        "output.json",
        "backup.zip",
        "config.yml",
    ],
    "folder": [
        "Desktop",
        "Documents",
        "Downloads",
        "Projects",
        "Archive",
        "Backup",
        "Work",
        "Photos",
        "Music",
        "Temp",
    ],
    "email": [
        "john@example.com",
        "alice@work.com",
        "boss@company.com",
        "support@service.com",
        "friend@gmail.com",
        "team@startup.io",
        "hr@bigcorp.com",
        "dev@openai.com",
    ],
    "slack_channel": [
        "#general",
        "#engineering",
        "#random",
        "#team-updates",
        "#announcements",
        "#design",
        "#support",
        "#standups",
    ],
}


def generate_variations(template: str, num_variations: int = 15) -> list[str]:
    """Fill template placeholders with random filler values."""
    variations = []
    placeholders = re.findall(r"\{(\w+)\}", template)

    if not placeholders:
        # Static templates: return exactly one copy (dedup handles the rest)
        return [template]

    for _ in range(num_variations):
        text = template
        for ph in placeholders:
            if ph in FILLERS:
                text = text.replace(f"{{{ph}}}", random.choice(FILLERS[ph]))
        variations.append(text)
    return list(set(variations))  # Deduplicate


def main() -> None:
    print("Generating training data for tool classifier...")
    random.seed(42)  # Reproducible output
    dataset: list[dict[str, str]] = []

    for label, templates in DATASET_TEMPLATES.items():
        label_examples: list[str] = []
        for template in templates:
            label_examples.extend(generate_variations(template, num_variations=20))

        # De-duplicate within label
        label_examples = list(set(label_examples))

        augmented: list[dict[str, str]] = []
        for text in label_examples:
            augmented.append({"text": text, "label": label})
            # Case/punctuation augmentation
            augmented.append({"text": text.lower().rstrip("?"), "label": label})

        dataset.extend(augmented)
        print(f"  {label:35s} -> {len(augmented):4d} examples")

    print(f"\nTotal dataset size: {len(dataset)} examples across {len(DATASET_TEMPLATES)} classes")

    if len(dataset) < 500:
        print("WARNING: Dataset has fewer than 500 examples. Add more templates!")

    # Save to data directory
    data_dir = Path(__file__).parent.parent / "data"
    data_dir.mkdir(exist_ok=True)

    output_path = data_dir / "training_data.json"
    with output_path.open("w", encoding="utf-8") as f:
        json.dump(dataset, f, indent=2, ensure_ascii=False)

    print(f"\nSaved dataset to {output_path}")


if __name__ == "__main__":
    main()
