r"""
Retrain the TF-IDF + SVM tool classifier using the current sklearn version.
Run from the project root with the .venv active:
  .venv\Scripts\python scripts\retrain_classifier.py
"""

from pathlib import Path

import joblib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC


# ---------------------------------------------------------------------------
# TRAINING DATA  — (query, tool_name) pairs
# ---------------------------------------------------------------------------
TRAINING_DATA = [
    # open_program
    ("run vlc", "open_program"),
    ("open chrome", "open_program"),
    ("launch firefox", "open_program"),
    ("open discord", "open_program"),
    ("open whatsapp", "open_program"),
    ("run firefox", "open_program"),
    ("run visual studio code", "open_program"),
    ("launch word", "open_program"),
    ("start spotify", "open_program"),
    ("boot up whatsapp", "open_program"),
    ("start visual studio code", "open_program"),
    ("launch visual studio code", "open_program"),
    ("launch notepad", "open_program"),
    ("open word", "open_program"),
    ("start chrome", "open_program"),
    ("start vlc", "open_program"),
    ("run discord", "open_program"),
    ("start whatsapp", "open_program"),
    ("launch discord", "open_program"),
    ("launch chrome", "open_program"),
    ("open visual studio code", "open_program"),
    ("run spotify", "open_program"),
    ("open firefox", "open_program"),
    ("open vlc", "open_program"),
    ("run whatsapp", "open_program"),
    # terminate_program
    ("close chrome", "terminate_program"),
    ("force quit system process", "terminate_program"),
    ("force quit chrome", "terminate_program"),
    ("stop system process", "terminate_program"),
    ("close notepad", "terminate_program"),
    ("end process for chrome", "terminate_program"),
    ("force quit notepad", "terminate_program"),
    ("kill spotify", "terminate_program"),
    ("close vlc", "terminate_program"),
    ("force quit vlc", "terminate_program"),
    ("force quit spotify", "terminate_program"),
    ("terminate chrome", "terminate_program"),
    ("close system process", "terminate_program"),
    ("end process for system process", "terminate_program"),
    ("end process for spotify", "terminate_program"),
    ("end process for firefox", "terminate_program"),
    ("terminate system process", "terminate_program"),
    ("stop chrome", "terminate_program"),
    ("kill system process", "terminate_program"),
    ("kill firefox", "terminate_program"),
    ("close spotify", "terminate_program"),
    ("terminate notepad", "terminate_program"),
    ("terminate firefox", "terminate_program"),
    ("stop firefox", "terminate_program"),
    ("terminate vlc", "terminate_program"),
    # get_datetime_info
    ("what time is it right now", "get_datetime_info"),
    ("what day is it right now", "get_datetime_info"),
    ("what day is it currently", "get_datetime_info"),
    ("date please in my timezone", "get_datetime_info"),
    ("date please right now", "get_datetime_info"),
    ("date please today", "get_datetime_info"),
    ("tell me the time right now", "get_datetime_info"),
    ("what is today's date now", "get_datetime_info"),
    ("date please now", "get_datetime_info"),
    ("what time is it currently", "get_datetime_info"),
    ("what is today's date currently", "get_datetime_info"),
    ("what is today's date today", "get_datetime_info"),
    ("current time please today", "get_datetime_info"),
    ("tell me the time now", "get_datetime_info"),
    ("what is today's date right now", "get_datetime_info"),
    ("current time please in my timezone", "get_datetime_info"),
    ("current time please now", "get_datetime_info"),
    ("date please currently", "get_datetime_info"),
    ("what time is it in my timezone", "get_datetime_info"),
    ("what day is it now", "get_datetime_info"),
    ("what time is it today", "get_datetime_info"),
    ("tell me the time today", "get_datetime_info"),
    ("tell me the time currently", "get_datetime_info"),
    ("what time is it now", "get_datetime_info"),
    ("current time please right now", "get_datetime_info"),
    # get_weather
    ("how is the weather tomorrow", "get_weather"),
    ("how is the weather today", "get_weather"),
    ("temperature outside outside", "get_weather"),
    ("temperature outside in paris", "get_weather"),
    ("will it rain outside", "get_weather"),
    ("will it rain in london", "get_weather"),
    ("what is the weather in paris", "get_weather"),
    ("what is the weather outside", "get_weather"),
    ("what is the weather today", "get_weather"),
    ("will it rain today", "get_weather"),
    ("what is the weather tomorrow", "get_weather"),
    ("is it hot this weekend", "get_weather"),
    ("weather forecast tomorrow", "get_weather"),
    ("how is the weather outside", "get_weather"),
    ("is it hot tomorrow", "get_weather"),
    ("temperature outside tomorrow", "get_weather"),
    ("how is the weather in paris", "get_weather"),
    ("weather forecast this weekend", "get_weather"),
    ("how is the weather this weekend", "get_weather"),
    ("is it hot outside", "get_weather"),
    ("temperature outside in london", "get_weather"),
    ("how is the weather in london", "get_weather"),
    ("what is the weather this weekend", "get_weather"),
    ("temperature outside this weekend", "get_weather"),
    ("temperature outside today", "get_weather"),
    # web_search
    ("find information about quantum physics", "web_search"),
    ("search youtube for quantum physics", "web_search"),
    ("search the web for elon musk", "web_search"),
    ("google latest ai news", "web_search"),
    ("search youtube for funny cat videos", "web_search"),
    ("google funny cat videos", "web_search"),
    ("search the web for python tutorials", "web_search"),
    ("look up elon musk", "web_search"),
    ("search the web for programming tips", "web_search"),
    ("search the web for latest ai news", "web_search"),
    ("google quantum physics", "web_search"),
    ("search the web for quantum physics", "web_search"),
    ("look up funny cat videos", "web_search"),
    ("search for funny cat videos", "web_search"),
    ("google python tutorials", "web_search"),
    ("look up programming tips", "web_search"),
    ("google programming tips", "web_search"),
    ("search for python tutorials", "web_search"),
    ("search for quantum physics", "web_search"),
    ("search for latest ai news", "web_search"),
    ("google elon musk", "web_search"),
    ("search youtube for elon musk", "web_search"),
    ("look up quantum physics", "web_search"),
    ("find information about elon musk", "web_search"),
    ("find information about funny cat videos", "web_search"),
    # wikipedia_search
    ("search wikipedia for alan turing", "wikipedia_search"),
    ("tell me about black holes", "wikipedia_search"),
    ("tell me about machine learning", "wikipedia_search"),
    ("summarize quantum computing", "wikipedia_search"),
    ("what is relativity", "wikipedia_search"),
    ("who is quantum computing", "wikipedia_search"),
    ("tell me about quantum computing", "wikipedia_search"),
    ("summarize world war two", "wikipedia_search"),
    ("what is alan turing", "wikipedia_search"),
    ("search wikipedia for world war two", "wikipedia_search"),
    ("search wikipedia for quantum computing", "wikipedia_search"),
    ("explain world war two", "wikipedia_search"),
    ("tell me about world war two", "wikipedia_search"),
    ("summarize machine learning", "wikipedia_search"),
    ("who is machine learning", "wikipedia_search"),
    ("summarize black holes", "wikipedia_search"),
    ("explain machine learning", "wikipedia_search"),
    ("summarize alan turing", "wikipedia_search"),
    ("what is world war two", "wikipedia_search"),
    ("tell me about relativity", "wikipedia_search"),
    ("who is world war two", "wikipedia_search"),
    ("who is relativity", "wikipedia_search"),
    ("explain quantum computing", "wikipedia_search"),
    ("explain relativity", "wikipedia_search"),
    ("explain black holes", "wikipedia_search"),
    # search_file
    ("locate file report.pdf", "search_file"),
    ("search for a pdf named notes.txt", "search_file"),
    ("locate file notes.txt", "search_file"),
    ("find a file named invoice", "search_file"),
    ("where did i save invoice", "search_file"),
    ("search my computer for how to be alone", "search_file"),
    ("where is the file how to be alone", "search_file"),
    ("where is the file presentation", "search_file"),
    ("search my computer for invoice", "search_file"),
    ("search for a pdf named presentation", "search_file"),
    ("where is the file budget.xlsx", "search_file"),
    ("find a file named presentation", "search_file"),
    ("search for a pdf named report.pdf", "search_file"),
    ("locate file presentation", "search_file"),
    ("find a file named budget.xlsx", "search_file"),
    ("locate file budget.xlsx", "search_file"),
    ("where is the file notes.txt", "search_file"),
    ("search for a pdf named invoice", "search_file"),
    ("search my computer for budget.xlsx", "search_file"),
    ("locate file invoice", "search_file"),
    ("search for a pdf named budget.xlsx", "search_file"),
    ("where did i save report.pdf", "search_file"),
    ("where did i save presentation", "search_file"),
    ("search my computer for presentation", "search_file"),
    ("where is the file invoice", "search_file"),
    # set_volume
    ("unmute volume level 5", "set_volume"),
    ("unmute volume max", "set_volume"),
    ("increase volume max", "set_volume"),
    ("change volume to minimum", "set_volume"),
    ("change volume to max", "set_volume"),
    ("lower the volume max", "set_volume"),
    ("unmute volume a bit", "set_volume"),
    ("set volume to a bit", "set_volume"),
    ("set volume to 50", "set_volume"),
    ("mute the sound max", "set_volume"),
    ("unmute volume minimum", "set_volume"),
    ("increase volume minimum", "set_volume"),
    ("increase volume 50", "set_volume"),
    ("change volume to level 5", "set_volume"),
    ("increase volume a bit", "set_volume"),
    ("lower the volume minimum", "set_volume"),
    ("lower the volume level 5", "set_volume"),
    ("mute the sound 70%", "set_volume"),
    ("lower the volume a bit", "set_volume"),
    ("mute the sound a bit", "set_volume"),
    ("unmute volume 50", "set_volume"),
    ("change volume to 50", "set_volume"),
    ("change volume to 70%", "set_volume"),
    ("unmute volume 70%", "set_volume"),
    ("mute the sound 50", "set_volume"),
    # get_volume
    ("check volume currently", "get_volume"),
    ("current volume level right now", "get_volume"),
    ("current volume level on my pc", "get_volume"),
    ("is volume muted on my pc", "get_volume"),
    ("check volume", "get_volume"),
    ("how loud is it on my pc", "get_volume"),
    ("what is the current volume on my pc", "get_volume"),
    ("is volume muted currently", "get_volume"),
    ("what is the current volume right now", "get_volume"),
    ("show volume", "get_volume"),
    ("current volume level currently", "get_volume"),
    ("check volume right now", "get_volume"),
    ("check volume on my pc", "get_volume"),
    ("check volume on the system", "get_volume"),
    ("is volume muted right now", "get_volume"),
    ("show volume on my pc", "get_volume"),
    ("how loud is it right now", "get_volume"),
    ("check volume please", "get_volume"),
    ("is volume muted please", "get_volume"),
    ("current volume level please", "get_volume"),
    ("is volume muted", "get_volume"),
    ("how loud is it on the system", "get_volume"),
    ("how loud is it currently", "get_volume"),
    ("show volume currently", "get_volume"),
    ("show volume right now", "get_volume"),
    # set_brightness
    ("increase brightness minimum", "set_brightness"),
    ("lower screen brightness level 10", "set_brightness"),
    ("increase brightness max", "set_brightness"),
    ("increase brightness level 10", "set_brightness"),
    ("lower screen brightness minimum", "set_brightness"),
    ("set brightness to a little", "set_brightness"),
    ("dim the screen to max", "set_brightness"),
    ("screen too bright lower it level 10", "set_brightness"),
    ("lower screen brightness 50%", "set_brightness"),
    ("change brightness to 70", "set_brightness"),
    ("change brightness to a little", "set_brightness"),
    ("increase brightness 70", "set_brightness"),
    ("change brightness to minimum", "set_brightness"),
    ("screen too bright lower it 70", "set_brightness"),
    ("screen too bright lower it 50%", "set_brightness"),
    ("change brightness to max", "set_brightness"),
    ("screen too bright lower it a little", "set_brightness"),
    ("change brightness to level 10", "set_brightness"),
    ("set brightness to minimum", "set_brightness"),
    ("screen too bright lower it minimum", "set_brightness"),
    ("set brightness to level 10", "set_brightness"),
    ("change brightness to 50%", "set_brightness"),
    ("screen too bright lower it max", "set_brightness"),
    ("set brightness to 70", "set_brightness"),
    ("set brightness to max", "set_brightness"),
    # take_screenshot
    ("snap the screen quickly", "take_screenshot"),
    ("capture the screen quickly", "take_screenshot"),
    ("snap the screen of this window", "take_screenshot"),
    ("take a screenshot of this window", "take_screenshot"),
    ("screenshot now", "take_screenshot"),
    ("capture the screen of this window", "take_screenshot"),
    ("snap the screen please", "take_screenshot"),
    ("screenshot the current screen please", "take_screenshot"),
    ("take a screen capture quickly", "take_screenshot"),
    ("screenshot the current screen for me", "take_screenshot"),
    ("take a screenshot quickly", "take_screenshot"),
    ("take a screenshot now", "take_screenshot"),
    ("take a screenshot for me", "take_screenshot"),
    ("screenshot", "take_screenshot"),
    ("snap the screen", "take_screenshot"),
    ("screenshot the current screen of this window", "take_screenshot"),
    ("take a screen capture for me", "take_screenshot"),
    ("take a screen capture of this window", "take_screenshot"),
    ("screenshot the current screen", "take_screenshot"),
    ("capture the screen please", "take_screenshot"),
    ("snap the screen for me", "take_screenshot"),
    ("screenshot for me", "take_screenshot"),
    ("take a screen capture please", "take_screenshot"),
    ("capture the screen for me", "take_screenshot"),
    ("take a screen capture", "take_screenshot"),
    # list_open_apps
    ("what programs are running", "list_open_apps"),
    ("what's open right now please", "list_open_apps"),
    ("what programs are running please", "list_open_apps"),
    ("what apps do i have open currently", "list_open_apps"),
    ("show open apps please", "list_open_apps"),
    ("what's open right now right now", "list_open_apps"),
    ("what's open right now", "list_open_apps"),
    ("what apps do i have open right now", "list_open_apps"),
    ("list running applications currently", "list_open_apps"),
    ("what apps do i have open in the background", "list_open_apps"),
    ("show open apps", "list_open_apps"),
    ("open windows", "list_open_apps"),
    ("what's open right now on my pc", "list_open_apps"),
    ("list running applications in the background", "list_open_apps"),
    ("what's open right now in the background", "list_open_apps"),
    ("open windows right now", "list_open_apps"),
    ("open windows please", "list_open_apps"),
    ("show open apps right now", "list_open_apps"),
    ("what programs are running in the background", "list_open_apps"),
    ("open windows on my pc", "list_open_apps"),
    ("what programs are running currently", "list_open_apps"),
    ("list running applications right now", "list_open_apps"),
    ("show open apps on my pc", "list_open_apps"),
    ("list running applications on my pc", "list_open_apps"),
    ("what programs are running on my pc", "list_open_apps"),
    # get_news
    ("show me news about technology", "get_news"),
    ("current events middle east", "get_news"),
    ("news from india", "get_news"),
    ("current events technology", "get_news"),
    ("today's top headlines india", "get_news"),
    ("latest news india", "get_news"),
    ("what happened in the world today technology", "get_news"),
    ("today's top headlines technology", "get_news"),
    ("show me news about politics", "get_news"),
    ("show me news about tech", "get_news"),
    ("show me news about middle east", "get_news"),
    ("current events india", "get_news"),
    ("show me news about india", "get_news"),
    ("news from tech", "get_news"),
    ("what happened in the world today tech", "get_news"),
    ("latest news usa", "get_news"),
    ("news from politics", "get_news"),
    ("what happened in the world today middle east", "get_news"),
    ("today's top headlines politics", "get_news"),
    ("today's top headlines middle east", "get_news"),
    ("today's top headlines usa", "get_news"),
    ("news from usa", "get_news"),
    ("what happened in the world today india", "get_news"),
    ("today's top headlines tech", "get_news"),
    ("latest news tech", "get_news"),
    # get_cpu_usage
    ("is cpu overloaded on this machine", "get_cpu_usage"),
    ("cpu usage right now", "get_cpu_usage"),
    ("check cpu please", "get_cpu_usage"),
    ("show processor stats on this machine", "get_cpu_usage"),
    ("check cpu today", "get_cpu_usage"),
    ("show processor stats", "get_cpu_usage"),
    ("processor load on this machine", "get_cpu_usage"),
    ("how is my cpu on this machine", "get_cpu_usage"),
    ("processor load today", "get_cpu_usage"),
    ("is cpu overloaded currently", "get_cpu_usage"),
    ("cpu usage today", "get_cpu_usage"),
    ("processor load currently", "get_cpu_usage"),
    ("processor load please", "get_cpu_usage"),
    ("how is my cpu", "get_cpu_usage"),
    ("how is my cpu please", "get_cpu_usage"),
    ("how is my cpu currently", "get_cpu_usage"),
    ("is cpu overloaded", "get_cpu_usage"),
    ("show processor stats today", "get_cpu_usage"),
    ("cpu usage on this machine", "get_cpu_usage"),
    ("show processor stats right now", "get_cpu_usage"),
    ("show processor stats currently", "get_cpu_usage"),
    ("is cpu overloaded right now", "get_cpu_usage"),
    ("how is my cpu today", "get_cpu_usage"),
    ("cpu usage please", "get_cpu_usage"),
    ("is cpu overloaded please", "get_cpu_usage"),
    # get_memory_usage
    ("how much memory is free", "get_memory_usage"),
    ("memory usage", "get_memory_usage"),
    ("is ram full", "get_memory_usage"),
    ("ram stats on the system", "get_memory_usage"),
    ("is ram full on the system", "get_memory_usage"),
    ("check memory currently", "get_memory_usage"),
    ("ram stats please", "get_memory_usage"),
    ("memory usage on the system", "get_memory_usage"),
    ("how much ram am i using", "get_memory_usage"),
    ("how much memory is free right now", "get_memory_usage"),
    ("how much ram am i using please", "get_memory_usage"),
    ("memory usage right now", "get_memory_usage"),
    ("check memory", "get_memory_usage"),
    ("ram stats", "get_memory_usage"),
    ("memory usage today", "get_memory_usage"),
    ("how much ram am i using on the system", "get_memory_usage"),
    ("how much memory is free please", "get_memory_usage"),
    ("ram stats today", "get_memory_usage"),
    ("how much memory is free currently", "get_memory_usage"),
    ("how much memory is free today", "get_memory_usage"),
    ("how much memory is free on the system", "get_memory_usage"),
    ("is ram full today", "get_memory_usage"),
    ("how much ram am i using currently", "get_memory_usage"),
    ("check memory today", "get_memory_usage"),
    ("ram stats right now", "get_memory_usage"),
    # get_disk_usage
    ("how full is my hard drive today", "get_disk_usage"),
    ("storage left currently", "get_disk_usage"),
    ("free space on disk currently", "get_disk_usage"),
    ("storage left please", "get_disk_usage"),
    ("storage left", "get_disk_usage"),
    ("ssd space right now", "get_disk_usage"),
    ("storage left on c drive", "get_disk_usage"),
    ("ssd space on c drive", "get_disk_usage"),
    ("disk space please", "get_disk_usage"),
    ("check disk usage on c drive", "get_disk_usage"),
    ("check disk usage please", "get_disk_usage"),
    ("ssd space currently", "get_disk_usage"),
    ("check disk usage currently", "get_disk_usage"),
    ("storage left today", "get_disk_usage"),
    ("check disk usage right now", "get_disk_usage"),
    ("how full is my hard drive", "get_disk_usage"),
    ("storage left right now", "get_disk_usage"),
    ("how full is my hard drive currently", "get_disk_usage"),
    ("disk space currently", "get_disk_usage"),
    ("free space on disk", "get_disk_usage"),
    ("disk space on c drive", "get_disk_usage"),
    ("ssd space", "get_disk_usage"),
    ("check disk usage", "get_disk_usage"),
    ("check disk usage today", "get_disk_usage"),
    ("disk space today", "get_disk_usage"),
    # get_battery_info
    ("how much battery is left", "get_battery_info"),
    ("battery percentage", "get_battery_info"),
    ("power plugged in currently", "get_battery_info"),
    ("battery percentage currently", "get_battery_info"),
    ("power plugged in right now", "get_battery_info"),
    ("how much battery is left right now", "get_battery_info"),
    ("battery percentage today", "get_battery_info"),
    ("battery percentage please", "get_battery_info"),
    ("how much battery is left on my laptop", "get_battery_info"),
    ("is it charging please", "get_battery_info"),
    ("is it charging right now", "get_battery_info"),
    ("power plugged in please", "get_battery_info"),
    ("how much battery is left please", "get_battery_info"),
    ("how much battery is left today", "get_battery_info"),
    ("battery status", "get_battery_info"),
    ("power plugged in", "get_battery_info"),
    ("laptop battery please", "get_battery_info"),
    ("battery status today", "get_battery_info"),
    ("laptop battery", "get_battery_info"),
    ("battery percentage right now", "get_battery_info"),
    ("battery status on my laptop", "get_battery_info"),
    ("power plugged in on my laptop", "get_battery_info"),
    ("battery status currently", "get_battery_info"),
    ("is it charging today", "get_battery_info"),
    ("how much battery is left currently", "get_battery_info"),
    # system_status
    ("is the computer okay today", "system_status"),
    ("how is the system running currently", "system_status"),
    ("check system health today", "system_status"),
    ("is the computer okay", "system_status"),
    ("system status overall", "system_status"),
    ("is the computer okay right now", "system_status"),
    ("how is the system running", "system_status"),
    ("system overview currently", "system_status"),
    ("how is the system running overall", "system_status"),
    ("system status currently", "system_status"),
    ("check system health right now", "system_status"),
    ("system overview please", "system_status"),
    ("system overview", "system_status"),
    ("check system health currently", "system_status"),
    ("system overview overall", "system_status"),
    ("how is the system running please", "system_status"),
    ("is the computer okay overall", "system_status"),
    ("system status today", "system_status"),
    ("system status", "system_status"),
    ("system overview right now", "system_status"),
    ("system status please", "system_status"),
    ("is the computer okay please", "system_status"),
    ("check system health", "system_status"),
    ("how is the system running right now", "system_status"),
    ("how is the system running today", "system_status"),
    # get_full_system_report
    ("run a system report", "get_full_system_report"),
    ("complete system diagnostics please", "get_full_system_report"),
    ("full hardware report for this pc", "get_full_system_report"),
    ("detailed system info now", "get_full_system_report"),
    ("give me a full system report", "get_full_system_report"),
    ("run a system report quickly", "get_full_system_report"),
    ("give me a full system report please", "get_full_system_report"),
    ("run a system report please", "get_full_system_report"),
    ("full hardware report quickly", "get_full_system_report"),
    ("detailed system info today", "get_full_system_report"),
    ("run a system report now", "get_full_system_report"),
    ("full hardware report", "get_full_system_report"),
    ("full hardware report please", "get_full_system_report"),
    ("complete system diagnostics today", "get_full_system_report"),
    ("full hardware report now", "get_full_system_report"),
    ("complete system diagnostics now", "get_full_system_report"),
    ("detailed system info", "get_full_system_report"),
    ("give me a full system report quickly", "get_full_system_report"),
    ("complete system diagnostics for this pc", "get_full_system_report"),
    ("complete system diagnostics quickly", "get_full_system_report"),
    ("run a system report for this pc", "get_full_system_report"),
    ("complete system diagnostics", "get_full_system_report"),
    ("full hardware report today", "get_full_system_report"),
    ("detailed system info please", "get_full_system_report"),
    ("detailed system info for this pc", "get_full_system_report"),
    # check_system_alerts
    ("any system warnings now", "check_system_alerts"),
    ("any system warnings", "check_system_alerts"),
    ("check system alerts quickly", "check_system_alerts"),
    ("check system alerts today", "check_system_alerts"),
    ("performance alerts now", "check_system_alerts"),
    ("performance alerts please", "check_system_alerts"),
    ("any critical alerts quickly", "check_system_alerts"),
    ("any critical alerts today", "check_system_alerts"),
    ("any system warnings for this pc", "check_system_alerts"),
    ("check system alerts please", "check_system_alerts"),
    ("any critical alerts please", "check_system_alerts"),
    ("check system health for this pc", "check_system_alerts"),
    ("performance alerts quickly", "check_system_alerts"),
    ("check system alerts", "check_system_alerts"),
    ("any system warnings please", "check_system_alerts"),
    ("performance alerts for this pc", "check_system_alerts"),
    ("check system health please", "check_system_alerts"),
    ("any system warnings today", "check_system_alerts"),
    ("check system health now", "check_system_alerts"),
    ("check system health", "check_system_alerts"),
    ("check system alerts for this pc", "check_system_alerts"),
    ("check system health quickly", "check_system_alerts"),
    ("any critical alerts now", "check_system_alerts"),
    ("performance alerts", "check_system_alerts"),
    ("any critical alerts", "check_system_alerts"),
    # get_running_processes
    ("show running processes quickly", "get_running_processes"),
    ("what is eating my ram quickly", "get_running_processes"),
    ("show running processes", "get_running_processes"),
    ("what is eating my ram now", "get_running_processes"),
    ("top processes for this pc", "get_running_processes"),
    ("show running processes for this pc", "get_running_processes"),
    ("top processes quickly", "get_running_processes"),
    ("top processes today", "get_running_processes"),
    ("list background tasks now", "get_running_processes"),
    ("show running processes please", "get_running_processes"),
    ("top processes please", "get_running_processes"),
    ("what processes are running for this pc", "get_running_processes"),
    ("what processes are running today", "get_running_processes"),
    ("top processes", "get_running_processes"),
    ("show running processes today", "get_running_processes"),
    ("what processes are running please", "get_running_processes"),
    ("what is eating my ram for this pc", "get_running_processes"),
    ("list background tasks today", "get_running_processes"),
    ("what processes are running quickly", "get_running_processes"),
    ("what processes are running", "get_running_processes"),
    ("what is eating my ram", "get_running_processes"),
    ("top processes now", "get_running_processes"),
    ("list background tasks please", "get_running_processes"),
    ("list background tasks for this pc", "get_running_processes"),
    ("what processes are running now", "get_running_processes"),
    # get_network_info
    ("check network usage please", "get_network_info"),
    ("network statistics today", "get_network_info"),
    ("network info quickly", "get_network_info"),
    ("internet usage now", "get_network_info"),
    ("how much data have i sent today", "get_network_info"),
    ("how much data have i sent quickly", "get_network_info"),
    ("network info today", "get_network_info"),
    ("how much data have i sent please", "get_network_info"),
    ("network statistics please", "get_network_info"),
    ("internet usage please", "get_network_info"),
    ("check network usage now", "get_network_info"),
    ("how much data have i sent for this pc", "get_network_info"),
    ("network statistics quickly", "get_network_info"),
    ("check network usage today", "get_network_info"),
    ("check network usage for this pc", "get_network_info"),
    ("check network usage", "get_network_info"),
    ("internet usage today", "get_network_info"),
    ("network statistics for this pc", "get_network_info"),
    ("internet usage", "get_network_info"),
    ("how much data have i sent", "get_network_info"),
    ("network statistics now", "get_network_info"),
    ("check network usage quickly", "get_network_info"),
    ("internet usage quickly", "get_network_info"),
    ("network info for this pc", "get_network_info"),
    ("how much data have i sent now", "get_network_info"),
    # copy_file
    ("clone document", "copy_file"),
    ("clone document here", "copy_file"),
    ("copy report.pdf to desktop", "copy_file"),
    ("duplicate budget.xlsx to downloads", "copy_file"),
    ("copy file to downloads", "copy_file"),
    ("copy file", "copy_file"),
    ("copy file to desktop", "copy_file"),
    ("duplicate file to desktop", "copy_file"),
    ("copy report.pdf to documents", "copy_file"),
    ("clone document to downloads", "copy_file"),
    ("make a copy of to documents", "copy_file"),
    ("duplicate budget.xlsx", "copy_file"),
    ("copy report.pdf here", "copy_file"),
    ("clone document to desktop", "copy_file"),
    ("duplicate file here", "copy_file"),
    ("copy file to documents", "copy_file"),
    ("make a copy of to the folder", "copy_file"),
    ("copy report.pdf to downloads", "copy_file"),
    ("make a copy of to downloads", "copy_file"),
    ("duplicate budget.xlsx here", "copy_file"),
    ("clone document to the folder", "copy_file"),
    ("duplicate file to the folder", "copy_file"),
    ("duplicate file to downloads", "copy_file"),
    ("copy file here", "copy_file"),
    ("duplicate file to documents", "copy_file"),
    # move_file
    ("move file to the folder", "move_file"),
    ("move report.pdf here", "move_file"),
    ("move file to downloads", "move_file"),
    ("transfer document", "move_file"),
    ("relocate file to desktop", "move_file"),
    ("relocate file to documents", "move_file"),
    ("transfer budget.xlsx to desktop", "move_file"),
    ("transfer budget.xlsx to downloads", "move_file"),
    ("transfer budget.xlsx", "move_file"),
    ("relocate file to downloads", "move_file"),
    ("shift file", "move_file"),
    ("move report.pdf to the folder", "move_file"),
    ("relocate file here", "move_file"),
    ("move report.pdf to desktop", "move_file"),
    ("shift file to desktop", "move_file"),
    ("transfer budget.xlsx here", "move_file"),
    ("move report.pdf to documents", "move_file"),
    ("move file here", "move_file"),
    ("transfer budget.xlsx to the folder", "move_file"),
    ("move file to desktop", "move_file"),
    ("move report.pdf to downloads", "move_file"),
    ("transfer document to downloads", "move_file"),
    ("move report.pdf", "move_file"),
    ("shift file to the folder", "move_file"),
    ("move file to documents", "move_file"),
    # delete_file
    ("erase budget.xlsx", "delete_file"),
    ("delete document budget.xlsx", "delete_file"),
    ("delete the old backup old backup", "delete_file"),
    ("delete document notes.txt", "delete_file"),
    ("delete the old backup budget.xlsx", "delete_file"),
    ("erase", "delete_file"),
    ("remove file old backup", "delete_file"),
    ("remove file cache", "delete_file"),
    ("permanently delete notes.txt", "delete_file"),
    ("delete document old backup", "delete_file"),
    ("delete document report.pdf", "delete_file"),
    ("permanently delete report.pdf", "delete_file"),
    ("erase notes.txt", "delete_file"),
    ("permanently delete old backup", "delete_file"),
    ("remove file report.pdf", "delete_file"),
    ("delete the old backup notes.txt", "delete_file"),
    ("erase report.pdf", "delete_file"),
    ("trash file budget.xlsx", "delete_file"),
    ("permanently delete", "delete_file"),
    ("trash file old backup", "delete_file"),
    ("erase old backup", "delete_file"),
    ("trash file notes.txt", "delete_file"),
    ("permanently delete budget.xlsx", "delete_file"),
    ("delete document cache", "delete_file"),
    ("delete the old backup", "delete_file"),
    # create_folder
    ("create a new folder projects", "create_folder"),
    ("setup folder temp", "create_folder"),
    ("setup folder work", "create_folder"),
    ("setup folder personal", "create_folder"),
    ("create folder personal", "create_folder"),
    ("create folder downloads", "create_folder"),
    ("make directory work", "create_folder"),
    ("create a new folder temp", "create_folder"),
    ("new directory downloads", "create_folder"),
    ("setup folder archive", "create_folder"),
    ("new directory archive", "create_folder"),
    ("new directory personal", "create_folder"),
    ("make directory temp", "create_folder"),
    ("new directory projects", "create_folder"),
    ("create a new folder work", "create_folder"),
    ("setup folder downloads", "create_folder"),
    ("new directory work", "create_folder"),
    ("create folder projects", "create_folder"),
    ("make directory downloads", "create_folder"),
    ("make directory personal", "create_folder"),
    ("new directory temp", "create_folder"),
    ("make directory archive", "create_folder"),
    ("create folder work", "create_folder"),
    ("create a new folder personal", "create_folder"),
    ("create a new folder downloads", "create_folder"),
    # add_reminder
    ("set a reminder later", "add_reminder"),
    ("create a new reminder at 5pm", "add_reminder"),
    ("put on my schedule to call mom", "add_reminder"),
    ("set a reminder to pay bills", "add_reminder"),
    ("remind me to to pay bills", "add_reminder"),
    ("create a new reminder soon", "add_reminder"),
    ("set a reminder soon", "add_reminder"),
    ("put on my schedule soon", "add_reminder"),
    ("remind me to later", "add_reminder"),
    ("remind me to at 5pm", "add_reminder"),
    ("add a reminder for tomorrow", "add_reminder"),
    ("add a reminder at 5pm", "add_reminder"),
    ("create a new reminder to call mom", "add_reminder"),
    ("put on my schedule later", "add_reminder"),
    ("create a new reminder to pay bills", "add_reminder"),
    ("add a reminder later", "add_reminder"),
    ("put on my schedule for tomorrow", "add_reminder"),
    ("add a reminder to pay bills", "add_reminder"),
    ("put on my schedule to pay bills", "add_reminder"),
    ("add a reminder to call mom", "add_reminder"),
    ("create a new reminder for tomorrow", "add_reminder"),
    ("set a reminder for tomorrow", "add_reminder"),
    ("set a reminder to call mom", "add_reminder"),
    ("remind me to soon", "add_reminder"),
    ("put on my schedule at 5pm", "add_reminder"),
    # list_reminders
    ("what am i forgetting for today", "list_reminders"),
    ("what are my reminders please", "list_reminders"),
    ("what are my reminders in the system", "list_reminders"),
    ("list my reminders now", "list_reminders"),
    ("show reminders for today", "list_reminders"),
    ("list my reminders for today", "list_reminders"),
    ("what am i forgetting in the system", "list_reminders"),
    ("show reminders in the system", "list_reminders"),
    ("show reminders now", "list_reminders"),
    ("what are my reminders for today", "list_reminders"),
    ("what are my reminders for tomorrow", "list_reminders"),
    ("check reminders for today", "list_reminders"),
    ("what am i forgetting now", "list_reminders"),
    ("list my reminders please", "list_reminders"),
    ("check reminders now", "list_reminders"),
    ("check reminders please", "list_reminders"),
    ("check reminders", "list_reminders"),
    ("show reminders for tomorrow", "list_reminders"),
    ("show reminders", "list_reminders"),
    ("check reminders in the system", "list_reminders"),
    ("what am i forgetting", "list_reminders"),
    ("list my reminders for tomorrow", "list_reminders"),
    ("what am i forgetting for tomorrow", "list_reminders"),
    ("check reminders for tomorrow", "list_reminders"),
    ("what are my reminders now", "list_reminders"),
    # create_note
    ("take a note stuff to do", "create_note"),
    ("save a note stuff to do", "create_note"),
    ("save a note", "create_note"),
    ("create a note", "create_note"),
    ("write down stuff to do", "create_note"),
    ("save a note grocery list", "create_note"),
    ("take a note project ideas", "create_note"),
    ("save a note project ideas", "create_note"),
    ("save a note meeting notes", "create_note"),
    ("new note project ideas", "create_note"),
    ("new note passwords", "create_note"),
    ("jot down meeting notes", "create_note"),
    ("new note meeting notes", "create_note"),
    ("jot down stuff to do", "create_note"),
    ("write down", "create_note"),
    ("write down project ideas", "create_note"),
    ("create a note stuff to do", "create_note"),
    ("jot down", "create_note"),
    ("take a note passwords", "create_note"),
    ("new note", "create_note"),
    ("create a note meeting notes", "create_note"),
    ("write down meeting notes", "create_note"),
    ("write down passwords", "create_note"),
    ("create a note passwords", "create_note"),
    ("save a note passwords", "create_note"),
    # list_notes
    ("show my notes please", "list_notes"),
    ("read notes now", "list_notes"),
    ("what are my notes", "list_notes"),
    ("read notes in the system", "list_notes"),
    ("what are my notes all of them", "list_notes"),
    ("list all notes in the system", "list_notes"),
    ("display notes all of them", "list_notes"),
    ("list all notes for today", "list_notes"),
    ("what are my notes for today", "list_notes"),
    ("read notes", "list_notes"),
    ("display notes in the system", "list_notes"),
    ("read notes for today", "list_notes"),
    ("what are my notes please", "list_notes"),
    ("show my notes now", "list_notes"),
    ("list all notes please", "list_notes"),
    ("what are my notes in the system", "list_notes"),
    ("list all notes", "list_notes"),
    ("list all notes all of them", "list_notes"),
    ("show my notes all of them", "list_notes"),
    ("display notes now", "list_notes"),
    ("what are my notes now", "list_notes"),
    ("display notes", "list_notes"),
    ("show my notes for today", "list_notes"),
    ("show my notes in the system", "list_notes"),
    ("display notes please", "list_notes"),
    # schedule_future_task
    ("wait before task", "schedule_future_task"),
    ("schedule a task for later task", "schedule_future_task"),
    ("schedule a task for later", "schedule_future_task"),
    ("wait before action", "schedule_future_task"),
    ("schedule a task for later doing it", "schedule_future_task"),
    ("remind yourself in an hour action", "schedule_future_task"),
    ("do this in 10 minutes running", "schedule_future_task"),
    ("remind yourself in an hour", "schedule_future_task"),
    ("delay execution of action", "schedule_future_task"),
    ("delay execution of", "schedule_future_task"),
    ("delay execution of command", "schedule_future_task"),
    ("do this in 10 minutes", "schedule_future_task"),
    ("wait before running", "schedule_future_task"),
    ("delay execution of task", "schedule_future_task"),
    ("schedule a task for later running", "schedule_future_task"),
    ("remind yourself in an hour task", "schedule_future_task"),
    ("wait before doing it", "schedule_future_task"),
    ("do this in 10 minutes action", "schedule_future_task"),
    ("delay execution of doing it", "schedule_future_task"),
    ("schedule a task for later command", "schedule_future_task"),
    ("remind yourself in an hour doing it", "schedule_future_task"),
    ("remind yourself in an hour command", "schedule_future_task"),
    ("do this in 10 minutes task", "schedule_future_task"),
    ("wait before", "schedule_future_task"),
    ("wait before command", "schedule_future_task"),
    # calculate
    ("evaluate this expression 100-50", "calculate"),
    ("what is 15 * 6", "calculate"),
    ("calculate 2+2", "calculate"),
    ("solve math 50% of 200", "calculate"),
    ("solve math 15 * 6", "calculate"),
    ("compute 100 divided by 5", "calculate"),
    ("quick math 100 divided by 5", "calculate"),
    ("what is 25 times 4", "calculate"),
    ("solve math 25 times 4", "calculate"),
    ("compute 25 times 4", "calculate"),
    ("calculate 50% of 200", "calculate"),
    ("calculate 100 divided by 5", "calculate"),
    ("quick math 50% of 200", "calculate"),
    ("what is 2+2", "calculate"),
    ("quick math 15 * 6", "calculate"),
    ("solve math 100-50", "calculate"),
    ("calculate 25 times 4", "calculate"),
    ("quick math 25 times 4", "calculate"),
    ("what is 100-50", "calculate"),
    ("evaluate this expression 25 times 4", "calculate"),
    ("evaluate this expression 50% of 200", "calculate"),
    ("compute 50% of 200", "calculate"),
    ("solve math 2+2", "calculate"),
    ("quick math 100-50", "calculate"),
    ("what is 100 divided by 5", "calculate"),
    # convert_temperature
    ("convert 100 fahrenheit to celsius now", "convert_temperature"),
    ("fahrenheit equivalent now", "convert_temperature"),
    ("how hot is 30 celsius", "convert_temperature"),
    ("convert celsius to in celsius", "convert_temperature"),
    ("how hot is 30 celsius please", "convert_temperature"),
    ("how hot is 30 celsius now", "convert_temperature"),
    ("convert celsius to now", "convert_temperature"),
    ("convert 100 fahrenheit to celsius in celsius", "convert_temperature"),
    ("convert 100 fahrenheit to celsius in fahrenheit", "convert_temperature"),
    ("convert 100 fahrenheit to celsius", "convert_temperature"),
    ("temperature conversion in celsius", "convert_temperature"),
    ("convert celsius to", "convert_temperature"),
    ("fahrenheit equivalent please", "convert_temperature"),
    ("fahrenheit equivalent", "convert_temperature"),
    ("how hot is 30 celsius in fahrenheit", "convert_temperature"),
    ("temperature conversion", "convert_temperature"),
    ("how hot is 30 celsius in celsius", "convert_temperature"),
    ("convert celsius to please", "convert_temperature"),
    ("fahrenheit equivalent in fahrenheit", "convert_temperature"),
    ("convert celsius to in fahrenheit", "convert_temperature"),
    ("temperature conversion now", "convert_temperature"),
    ("temperature conversion in fahrenheit", "convert_temperature"),
    ("temperature conversion please", "convert_temperature"),
    ("convert 100 fahrenheit to celsius please", "convert_temperature"),
    ("fahrenheit equivalent in celsius", "convert_temperature"),
    # convert_length
    ("convert inches to in cm", "convert_length"),
    ("convert inches to in km", "convert_length"),
    ("convert 10 miles to in cm", "convert_length"),
    ("distance conversion in km", "convert_length"),
    ("how many kilometers in 5 miles in inches", "convert_length"),
    ("convert 10 miles to", "convert_length"),
    ("convert 10 miles to in inches", "convert_length"),
    ("how many kilometers in 5 miles in meters", "convert_length"),
    ("how many kilometers in 5 miles in cm", "convert_length"),
    ("distance conversion in cm", "convert_length"),
    ("convert 10 miles to in meters", "convert_length"),
    ("distance conversion in meters", "convert_length"),
    ("how long is 5 feet", "convert_length"),
    ("distance conversion in inches", "convert_length"),
    ("how long is 5 feet in cm", "convert_length"),
    ("how long is 5 feet in km", "convert_length"),
    ("convert inches to in inches", "convert_length"),
    ("convert inches to", "convert_length"),
    ("distance conversion", "convert_length"),
    ("convert inches to in meters", "convert_length"),
    ("how many kilometers in 5 miles", "convert_length"),
    ("how many kilometers in 5 miles in km", "convert_length"),
    ("how long is 5 feet in inches", "convert_length"),
    ("convert 10 miles to in km", "convert_length"),
    ("how long is 5 feet in meters", "convert_length"),
    # tell_joke
    ("crack a joke", "tell_joke"),
    ("crack a joke dad joke", "tell_joke"),
    ("tell me a joke funny", "tell_joke"),
    ("do you know any jokes please", "tell_joke"),
    ("do you know any jokes about programming", "tell_joke"),
    ("do you know any jokes now", "tell_joke"),
    ("do you know any jokes", "tell_joke"),
    ("tell me a joke please", "tell_joke"),
    ("do you know any jokes dad joke", "tell_joke"),
    ("say something funny dad joke", "tell_joke"),
    ("make me laugh now", "tell_joke"),
    ("crack a joke please", "tell_joke"),
    ("make me laugh funny", "tell_joke"),
    ("crack a joke now", "tell_joke"),
    ("make me laugh please", "tell_joke"),
    ("tell me a joke", "tell_joke"),
    ("crack a joke funny", "tell_joke"),
    ("make me laugh", "tell_joke"),
    ("tell me a joke about programming", "tell_joke"),
    ("say something funny", "tell_joke"),
    ("say something funny about programming", "tell_joke"),
    ("say something funny funny", "tell_joke"),
    ("do you know any jokes funny", "tell_joke"),
    ("make me laugh about programming", "tell_joke"),
    ("tell me a joke dad joke", "tell_joke"),
    # get_greeting
    ("who are you", "get_greeting"),
    ("hello amadeus", "get_greeting"),
    ("good morning system", "get_greeting"),
    ("greet me assistant", "get_greeting"),
    ("good evening amadeus", "get_greeting"),
    ("greet me amadeus", "get_greeting"),
    ("good morning", "get_greeting"),
    ("hi there friend", "get_greeting"),
    ("hi there", "get_greeting"),
    ("hello amadeus amadeus", "get_greeting"),
    ("who are you bot", "get_greeting"),
    ("who are you amadeus", "get_greeting"),
    ("good morning friend", "get_greeting"),
    ("greet me system", "get_greeting"),
    ("good morning amadeus", "get_greeting"),
    ("good evening system", "get_greeting"),
    ("hello amadeus assistant", "get_greeting"),
    ("hi there system", "get_greeting"),
    ("good evening assistant", "get_greeting"),
    ("good morning bot", "get_greeting"),
    ("hi there assistant", "get_greeting"),
    ("good evening friend", "get_greeting"),
    ("greet me", "get_greeting"),
    ("hi there amadeus", "get_greeting"),
    ("hello amadeus bot", "get_greeting"),
    # send_email
    ("write an email to manager", "send_email"),
    ("draft and send an email john", "send_email"),
    ("send email to someone", "send_email"),
    ("draft and send an email someone", "send_email"),
    ("send an email john", "send_email"),
    ("send a mail adityatawde9699@gmail.com", "send_email"),
    ("draft and send an email adityatawde9699@gmail.com", "send_email"),
    ("draft and send an email manager", "send_email"),
    ("write an email to someone", "send_email"),
    ("write an email to test@example.com", "send_email"),
    ("send email to manager", "send_email"),
    ("send a mail manager", "send_email"),
    ("send an email someone", "send_email"),
    ("send email to test@example.com", "send_email"),
    ("write an email to adityatawde9699@gmail.com", "send_email"),
    ("compose a message and email it boss", "send_email"),
    ("send an email boss", "send_email"),
    ("send a mail john", "send_email"),
    ("send a mail boss", "send_email"),
    ("send a mail test@example.com", "send_email"),
    ("send an email test@example.com", "send_email"),
    ("compose a message and email it john", "send_email"),
    ("compose a message and email it manager", "send_email"),
    ("send a mail someone", "send_email"),
    ("draft and send an email boss", "send_email"),
    # read_unread_emails
    ("check my inbox now", "read_unread_emails"),
    ("summarize my latest unread emails", "read_unread_emails"),
    ("summarize my latest unread emails now", "read_unread_emails"),
    ("read my emails today", "read_unread_emails"),
    ("show my message inbox quickly", "read_unread_emails"),
    ("check my inbox quickly", "read_unread_emails"),
    ("check my inbox", "read_unread_emails"),
    ("summarize my latest unread emails please", "read_unread_emails"),
    ("read my emails now", "read_unread_emails"),
    ("read my emails", "read_unread_emails"),
    ("show my message inbox today", "read_unread_emails"),
    ("read my emails quickly", "read_unread_emails"),
    ("what unread emails do I have now", "read_unread_emails"),
    ("show my message inbox for me", "read_unread_emails"),
    ("show my message inbox now", "read_unread_emails"),
    ("summarize my latest unread emails quickly", "read_unread_emails"),
    ("summarize my latest unread emails for me", "read_unread_emails"),
    ("what unread emails do I have for me", "read_unread_emails"),
    ("what unread emails do I have", "read_unread_emails"),
    ("what unread emails do I have please", "read_unread_emails"),
    ("show my message inbox please", "read_unread_emails"),
    ("what unread emails do I have quickly", "read_unread_emails"),
    ("check my inbox today", "read_unread_emails"),
    ("what unread emails do I have today", "read_unread_emails"),
    ("show my message inbox", "read_unread_emails"),
    # create_excel_spreadsheet
    ("generate a spreadsheet", "create_excel_spreadsheet"),
    ("new excel workbook for budget", "create_excel_spreadsheet"),
    ("create a worksheet data", "create_excel_spreadsheet"),
    ("generate a spreadsheet for tracking", "create_excel_spreadsheet"),
    ("new excel workbook data", "create_excel_spreadsheet"),
    ("create a worksheet with columns name and age", "create_excel_spreadsheet"),
    ("new excel workbook with columns name and age", "create_excel_spreadsheet"),
    ("create an excel spreadsheet with columns name and age", "create_excel_spreadsheet"),
    ("make an excel file", "create_excel_spreadsheet"),
    ("create an excel spreadsheet for budget", "create_excel_spreadsheet"),
    ("create a worksheet", "create_excel_spreadsheet"),
    ("create a worksheet for tracking", "create_excel_spreadsheet"),
    ("make an excel file for budget", "create_excel_spreadsheet"),
    ("new excel workbook", "create_excel_spreadsheet"),
    ("new excel workbook for tracking", "create_excel_spreadsheet"),
    ("generate a spreadsheet data", "create_excel_spreadsheet"),
    ("create an excel spreadsheet data", "create_excel_spreadsheet"),
    ("create an excel spreadsheet for tracking", "create_excel_spreadsheet"),
    ("generate a spreadsheet for budget", "create_excel_spreadsheet"),
    ("create a worksheet for budget", "create_excel_spreadsheet"),
    ("make an excel file for tracking", "create_excel_spreadsheet"),
    ("make an excel file data", "create_excel_spreadsheet"),
    ("make an excel file with columns name and age", "create_excel_spreadsheet"),
    ("create an excel spreadsheet", "create_excel_spreadsheet"),
    ("generate a spreadsheet with columns name and age", "create_excel_spreadsheet"),
    # create_word_document
    ("write a report in word quickly", "create_word_document"),
    ("draft a word document with contents hello world", "create_word_document"),
    ("write a report in word", "create_word_document"),
    ("make a word document with contents hello world", "create_word_document"),
    ("draft a word document quickly", "create_word_document"),
    ("create a docx with contents hello world", "create_word_document"),
    ("write a report in word for school", "create_word_document"),
    ("draft a word document", "create_word_document"),
    ("create a docx for work", "create_word_document"),
    ("create a docx for school", "create_word_document"),
    ("make a word document for school", "create_word_document"),
    ("make a word document for work", "create_word_document"),
    ("save a word file with contents hello world", "create_word_document"),
    ("save a word file", "create_word_document"),
    ("create a docx quickly", "create_word_document"),
    ("make a word document quickly", "create_word_document"),
    ("save a word file quickly", "create_word_document"),
    ("write a report in word with contents hello world", "create_word_document"),
    ("make a word document", "create_word_document"),
    ("write a report in word for work", "create_word_document"),
    ("save a word file for school", "create_word_document"),
    ("save a word file for work", "create_word_document"),
    ("draft a word document for work", "create_word_document"),
    ("draft a word document for school", "create_word_document"),
    ("create a docx", "create_word_document"),
    # conversational
    ("tell me about yourself okay", "conversational"),
    ("what is the meaning of life good job", "conversational"),
    ("who created you okay", "conversational"),
    ("tell me about yourself who are you", "conversational"),
    ("you are very helpful good job", "conversational"),
    ("thank you good job", "conversational"),
    ("thank you okay", "conversational"),
    ("tell me about yourself good job", "conversational"),
    ("you are very helpful okay", "conversational"),
    ("how are you doing amadeus", "conversational"),
    ("tell me about yourself", "conversational"),
    ("who created you", "conversational"),
    ("who created you thanks", "conversational"),
    ("who created you hello", "conversational"),
    ("tell me about yourself thanks", "conversational"),
    ("you are very helpful thanks", "conversational"),
    ("what is the meaning of life thanks", "conversational"),
    ("how are you doing amadeus thanks", "conversational"),
    ("who created you who are you", "conversational"),
    ("how are you doing amadeus okay", "conversational"),
    ("you are very helpful who are you", "conversational"),
    ("what is the meaning of life hello", "conversational"),
    ("you are very helpful", "conversational"),
    ("what is the meaning of life okay", "conversational"),
    ("how are you doing amadeus who are you", "conversational"),
    # set_timer
    ("buzz me in 5 minutes", "set_timer"),
    ("countdown 30 seconds", "set_timer"),
    ("countdown 1 hour", "set_timer"),
    ("run a timer for 5 minutes", "set_timer"),
    ("run a timer for 10 minutes", "set_timer"),
    ("buzz me in 10 minutes", "set_timer"),
    ("set a timer for 1 hour", "set_timer"),
    ("run a timer for", "set_timer"),
    ("start a timer for 10 minutes", "set_timer"),
    ("countdown", "set_timer"),
    ("start a timer for", "set_timer"),
    ("buzz me in", "set_timer"),
    ("buzz me in 30 seconds", "set_timer"),
    ("countdown 5 minutes", "set_timer"),
    ("start a timer for 2 minutes", "set_timer"),
    ("start a timer for 1 hour", "set_timer"),
    ("start a timer for 5 minutes", "set_timer"),
    ("set a timer for", "set_timer"),
    ("run a timer for 2 minutes", "set_timer"),
    ("countdown 10 minutes", "set_timer"),
    ("countdown 2 minutes", "set_timer"),
    ("buzz me in 1 hour", "set_timer"),
    ("run a timer for 1 hour", "set_timer"),
    ("set a timer for 10 minutes", "set_timer"),
    ("set a timer for 5 minutes", "set_timer"),
]

# ---------------------------------------------------------------------------
# TRAIN
# ---------------------------------------------------------------------------
texts = [t for t, _ in TRAINING_DATA]
labels = [label for _, label in TRAINING_DATA]

vectorizer = TfidfVectorizer(ngram_range=(1, 2), min_df=1, max_features=5000)
classifier = LinearSVC(C=1.0, max_iter=2000)

X = vectorizer.fit_transform(texts)
classifier.fit(X, labels)

# ---------------------------------------------------------------------------
# SAVE
# ---------------------------------------------------------------------------
model_dir = Path("Model")
model_dir.mkdir(exist_ok=True)
# Save artifacts to BOTH naming schemes to ensure full system synchronization
# Scheme 1: AmadeusService direct path
joblib.dump(vectorizer, model_dir / "tfidf_vectorizer.joblib")
joblib.dump(classifier, model_dir / "svm_classifier.joblib")

# Scheme 2: AgentOrchestrator / router path
joblib.dump(vectorizer, model_dir / "router_vectorizer.joblib")
joblib.dump(classifier, model_dir / "router_classifier.joblib")

print(f"[OK] Classifier retrained with {X.shape[0]} samples and {len(classifier.classes_)} classes.")
print(f"     Classes: {sorted(list(classifier.classes_))}")

# Quick sanity check
test_phrases = [
    "open vlc",
    "how are you",
    "what time is it",
    "cpu usage",
    "search for python tutorials",
    "read my unread emails",
    "send email to boss",
    "set volume to 50",
    "brightness 70%",
    "take a screenshot",
    "what's open right now",
    "political news from usa",
    "latest news",
    "mute the sound",
    "dim the screen",
]
print("\n--- Sanity Check ---")
for phrase in test_phrases:
    x = vectorizer.transform([phrase])
    pred = classifier.predict(x)[0]
    print(f"  '{phrase}' -> {pred}")
