"""Fix _setup() indentation in memory_service.py after ARCH-04 lock insertion."""
from pathlib import Path

FILE = Path("src/infra/memory_service.py")
content = FILE.read_text(encoding="utf-8")

# The broken block (after bad edit): try: on one line then body at wrong indent
OLD = (
    "        async with _get_qdrant_lock():\r\n"
    "            try:\r\n"
    "            # Using the same persist path but handled by Qdrant\r\n"
    "            from qdrant_client import AsyncQdrantClient\r\n"
    "            from qdrant_client.models import Distance, VectorParams\r\n"
    "\r\n"
    "            Path(str(self._settings.CHROMA_PERSIST_DIR)).mkdir(parents=True, exist_ok=True)\r\n"
    "\r\n"
    "            if _global_qdrant_client is None:\r\n"
    "                _global_qdrant_client = AsyncQdrantClient(path=self._settings.CHROMA_PERSIST_DIR)\r\n"
    "\r\n"
    "            self._client = _global_qdrant_client\r\n"
    "\r\n"
    "            # Setup embedding model first — must happen before collection creation\r\n"
    "            # so we know the correct vector dimension (384 local vs 768 Gemini)\r\n"
    "            self._setup_embedding_model()\r\n"
    "\r\n"
    "            if not self._enabled:\r\n"
    "                return\r\n"
    "\r\n"
    "            collection_name = self._settings.CHROMA_COLLECTION_NAME\r\n"
    "            embed_dim = getattr(self, \"_embed_dim\", 384)\r\n"
    "\r\n"
    "            # Check if collection exists with correct dimensions\r\n"
    "            if await self._client.collection_exists(collection_name=collection_name):\r\n"
    "                # Verify dimension matches — recreate if mismatched (e.g. switched embedder)\r\n"
    "                try:\r\n"
    "                    info = await self._client.get_collection(collection_name)\r\n"
    "                    existing_dim = info.config.params.vectors.size  # type: ignore[union-attr]\r\n"
    "                    if existing_dim != embed_dim:\r\n"
    "                        logger.warning(\r\n"
    "                            \"Qdrant collection dimension mismatch (%d vs %d). \"\r\n"
    "                            \"Dropping and recreating collection.\",\r\n"
    "                            existing_dim,\r\n"
    "                            embed_dim,\r\n"
    "                        )\r\n"
    "                        await self._client.delete_collection(collection_name)\r\n"
    "                        await self._client.create_collection(\r\n"
    "                            collection_name=collection_name,\r\n"
    "                            vectors_config=VectorParams(size=embed_dim, distance=Distance.COSINE),\r\n"
    "                        )\r\n"
    "                except Exception:\r\n"
    "                    pass  # Collection info check failed — leave it as-is\r\n"
    "            else:\r\n"
    "                await self._client.create_collection(\r\n"
    "                    collection_name=collection_name,\r\n"
    "                    vectors_config=VectorParams(size=embed_dim, distance=Distance.COSINE),\r\n"
    "                )\r\n"
    "\r\n"
    "            logger.info(\r\n"
    "                \"Qdrant memory initialized — collection=%s, dim=%d, persist_dir=%s\",\r\n"
    "                collection_name,\r\n"
    "                embed_dim,\r\n"
    "                self._settings.CHROMA_PERSIST_DIR,\r\n"
    "            )\r\n"
    "            self._initialized = True\r\n"
    "        except Exception as exc:\r\n"
    "            logger.exception(\"Qdrant setup failed — memory disabled: %s\", exc)\r\n"
    "            self._enabled = False\r\n"
)

NEW = (
    "        async with _get_qdrant_lock():\r\n"
    "            try:\r\n"
    "                # Using the same persist path but handled by Qdrant\r\n"
    "                from qdrant_client import AsyncQdrantClient\r\n"
    "                from qdrant_client.models import Distance, VectorParams\r\n"
    "\r\n"
    "                Path(str(self._settings.CHROMA_PERSIST_DIR)).mkdir(parents=True, exist_ok=True)\r\n"
    "\r\n"
    "                if _global_qdrant_client is None:\r\n"
    "                    _global_qdrant_client = AsyncQdrantClient(path=self._settings.CHROMA_PERSIST_DIR)\r\n"
    "\r\n"
    "                self._client = _global_qdrant_client\r\n"
    "\r\n"
    "                # Setup embedding model first — must happen before collection creation\r\n"
    "                # so we know the correct vector dimension (384 local vs 768 Gemini)\r\n"
    "                self._setup_embedding_model()\r\n"
    "\r\n"
    "                if not self._enabled:\r\n"
    "                    return\r\n"
    "\r\n"
    "                collection_name = self._settings.CHROMA_COLLECTION_NAME\r\n"
    "                embed_dim = getattr(self, \"_embed_dim\", 384)\r\n"
    "\r\n"
    "                # Check if collection exists with correct dimensions\r\n"
    "                if await self._client.collection_exists(collection_name=collection_name):\r\n"
    "                    # Verify dimension matches — recreate if mismatched (e.g. switched embedder)\r\n"
    "                    try:\r\n"
    "                        info = await self._client.get_collection(collection_name)\r\n"
    "                        existing_dim = info.config.params.vectors.size  # type: ignore[union-attr]\r\n"
    "                        if existing_dim != embed_dim:\r\n"
    "                            logger.warning(\r\n"
    "                                \"Qdrant collection dimension mismatch (%d vs %d). \"\r\n"
    "                                \"Dropping and recreating collection.\",\r\n"
    "                                existing_dim,\r\n"
    "                                embed_dim,\r\n"
    "                            )\r\n"
    "                            await self._client.delete_collection(collection_name)\r\n"
    "                            await self._client.create_collection(\r\n"
    "                                collection_name=collection_name,\r\n"
    "                                vectors_config=VectorParams(size=embed_dim, distance=Distance.COSINE),\r\n"
    "                            )\r\n"
    "                    except Exception:\r\n"
    "                        pass  # Collection info check failed — leave it as-is\r\n"
    "                else:\r\n"
    "                    await self._client.create_collection(\r\n"
    "                        collection_name=collection_name,\r\n"
    "                        vectors_config=VectorParams(size=embed_dim, distance=Distance.COSINE),\r\n"
    "                    )\r\n"
    "\r\n"
    "                logger.info(\r\n"
    "                    \"Qdrant memory initialized — collection=%s, dim=%d, persist_dir=%s\",\r\n"
    "                    collection_name,\r\n"
    "                    embed_dim,\r\n"
    "                    self._settings.CHROMA_PERSIST_DIR,\r\n"
    "                )\r\n"
    "                self._initialized = True\r\n"
    "            except Exception as exc:\r\n"
    "                logger.exception(\"Qdrant setup failed — memory disabled: %s\", exc)\r\n"
    "                self._enabled = False\r\n"
)

if OLD in content:
    content = content.replace(OLD, NEW, 1)
    FILE.write_text(content, encoding="utf-8")
    print("ARCH-04 _setup indentation fixed.")
else:
    print("ERROR: target block not found — manual fix needed")
